### ISSUE TITLE
getError always return an error even if touched is true

### ISSUE THREAD

**Issue by SBoudrias** [react-tools/react-form#100]
Right now, `getError` always return an error message if the field is invalid, even if it isn't marked a touched yet. I think this is fine, but it makes writing code using error strings a bit complicated.

I'm wondering if you'd be open to add a `getTouchedError` function API that would only return an error message if a field was actually touched?

**Comment by joepuzzo** [comment]
You can simply combine the touched and error values to achieve this functionality. If you really want some custom logic/style etc for your inputs, I would recommend creating your own custom fields via the FormField component. Also, stay tuned for V2 of react form, it will be published soon and the docs have example of how to create your own custom fields. When you do just use the getToucehd and getError functions that are exposed tot he formFields.

**Comment by SBoudrias** [comment]
@joepuzzo right now the issue is `<FormError />` always returns a components, so we need to combine a lot of logic to know if we need to display an error message or not. If it returned `null` when empty, this might also fix the problem without extra function.

**Comment by joepuzzo** [comment]
Check out https://react-form.js.org/#/custom-input and tell me if thats getting close to what you need. That custom input shows how to use the getError, getWarning, and getSuccess functions to hide or show messages. Would using the getTouched fix this issue?

**Comment by tannerlinsley** [comment]
@joepuzzo's new custom input HOC's should do the trick. This is much better now. Going to close for now.

**Comment by SBoudrias** [comment]
Hey guys, I've had some time to play with the new custom-input, and I don't think this match our use case.

The issue is custom inputs also always returns a value (a react component). I was initially hoping the custom components could returns null, but because of the dependency on `context`, we need to create an component instance; so the error is still always truthy.

What I need is a way to know outside of the form context if an error for `n` field is displayed or not.

Right now we just hack it with:

```js
const getTouchedError = field => {
    if (getTouched(field)) {
        return getError(field);
    }
    return undefined;
};
```

Any chance we could modify the current API to allow that? Could be adding a new function to `formApi` or maybe an option to `getError`? Like `getError(field, requireTouch)`?

**Comment by joepuzzo** [comment]
Why not just display error under this case ‘if( getTouched( field ) && getError( field )’

**Comment by joepuzzo** [comment]
In fact, I do this in all of my custom inputs AND I also have this check as well for another use case `if( getTouched( field ) && getValue( field )`. << that will only show error if user interacts with field.

**Comment by SBoudrias** [comment]
This just feel like a common enough use case that could be solved in react-form rather than everyone having to write the logic (+ unit tests) every time.

**Comment by joepuzzo** [comment]
Agreed but you really only have ti write one function and one test. It would start to get messy if react form had a function for every combination of getters. I get that u are asking for only one. But one simple helper method written once would solve your issue

**Comment by joepuzzo** [comment]
That being said i am working on an update that willl include what i call, styled inputs, that will apply classes to he inputs and have props for things like this.
