### ISSUE TITLE
Checkbox - conflicts with controlled/uncontrolled react requirements.

### ISSUE THREAD

**Issue by maxttor** [react-tools/react-form#101]
I'm use a code from example:
```
 <Checkbox
      field='createAccount'
    />
```

And get a warning:

> warning.js?85a7:35 Warning: FormField is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by Gaffen** [comment]
I can confirm that I'm getting this behaviour too

**Comment by thg303** [comment]
it's a duplicate of #91

**Comment by amaschas** [comment]
I was looking into this just now, and it seems like the issue is caused by the fact that the value of the checkbox input ends up behind `undefined` unless you set a default value. I'm not sure what the best way to handle this is though.

**Comment by joepuzzo** [comment]
Fixed this in latest version of V2
