### ISSUE TITLE
"Select" does not allow multiple choices

### ISSUE THREAD

**Issue by thg303** [react-tools/react-form#103]
"Select" component does not allow multiple selections.

**Comment by joepuzzo** [comment]
Hmm try to see if you can get fancy with creating your own custom select. See docs for how to create custom inputs.

**Comment by tannerlinsley** [comment]
@thg303 I would absolutely suggest wrapping something like https://github.com/paypal/downshift or https://github.com/JedWatson/react-select. React-Form's scope is not to provide every component, but instead provide a great and fast way to create your own components and reuse awesome components from the ecosystem.

Closing for now.

**Comment by tiffwu** [comment]
Could you add an example in the docs for how to wrap react-select? Currently struggling with this right now.
