### ISSUE TITLE
Access to event object in onSubmit

### ISSUE THREAD

**Issue by maxmatthews** [react-tools/react-form#108]
I'm trying to access data stored in `event` in the onSubmit prop. Specifically I want to check `event.shiftKey`, but with the current parameters, I can only access values, state, and props. Is there a way I can get into that data?

I'm trying to accomplish something like this: 
```jsx
import React from 'react'
import { Form, Text } from 'react-form'

const myForm = (
  <Form
    onSubmit={({values, event}) => { //need access to event here
      if (event.shiftKey){
        console.log('Shift Key Pressed When Clicking on Form Submit Button');
      } else {
        console.log('Just a regular form submission!')
      }
    }}
    validate={({ name }) => {
      return {
        name: !name ? 'A name is required' : undefined
      }
    }}
  >
    {({submitForm}) => {
      return (
        <form onSubmit={submitForm}>
          <Text field='name' />
          <button type='submit'>Submit (Clicking with shift does special things!)</button>
        </form>
      )
    }}
  </Form>
)
```

**Comment by maxmatthews** [comment]
@thg303 Any suggestions on this?

**Comment by thg303** [comment]
I don't know @maxmatthews, maybe it could be done easier with setting a keyboard event handler with `onKeyDown` attribute.

**Comment by maxmatthews** [comment]
Would https://github.com/tannerlinsley/react-form/pull/110 fix the issue?
If I do it in a onKeyDown, I have to manage the state which could get messy

**Comment by thg303** [comment]
@maxmatthews sure that PR would do the job. I don't have write access but @tannerlinsley would take a look at it soon.
If you're in rush you may release a scoped package and use it temporary ;)

**Comment by maxmatthews** [comment]
Awesome. As long as it's in the queue. Thanks!

**Comment by joepuzzo** [comment]
Hmm this is a good question. We are working on rolling out V2 of react-form and this is something we can look to add once we make the switch.
