### ISSUE TITLE
How operate tow selects cascade

### ISSUE THREAD

**Issue by skchen28** [react-tools/react-form#111]
Hi,everyone,I hava a question to ask. I have two selects, we can call one select A,and the other select B.Here comes the situation:select B's value depends on select A.Is there a eaxmple that help me understand how to handle the problem?

**Comment by thg303** [comment]
it's a little complicated scenario, but it's possible to do with a little effort.
You have to use `setValue` in the form to rewrite `onChange` event handler. something like this:
```
<Form  ... options1={['first', 'second', 'third']} >
{({values, setValue, options1}) => {
 <form>
   <Select field="fieldName"
     onChange={(e) => {
        setValue('filedName', options1[e.target.value - 1])
       // do more stuff like changing select B's options 
     }} 
   ... />
</form>
}}
</Form>
```

**Comment by tannerlinsley** [comment]
Closing for now. Reopen if needed.
