### ISSUE TITLE
Question: Add info about reducing bundle size to docs?

### ISSUE THREAD

**Issue by cherniavskii** [react-tools/react-form#114]
I'm using webpack for bundling, and I noticed that whole library gets into the bundle, even when I'm using only some parts of it. It looks like it's webpack issue, but e.g. `lodash` provides a solution for that - import like that:
`import assign from 'lodash/assign'`
instead of:
`import { assign } from 'lodash'`

It is also possible to import `react-form` in the same way:
`import Form from 'react-form/lib/form'`
instead of:
`import { Form } from 'react-form'`

In my case `react-form` size changed from `20,29Kb` (`4,19Kb` gzipped) to `8,73Kb` (`2,63Kb` gzipped) - since I only use `Form` and `FormField` from the package.
This solution will work with any bundler, not only with webpack, so it may be very useful.

What do you think about adding that info to docs in a similar way [lodash does](https://github.com/lodash/lodash#installation)?

**Comment by thg303** [comment]
excellent. I think it could be added to a separate part like "hints for production build" or something.

**Comment by cherniavskii** [comment]
Okay, I will submit a PR today or tomorrow ;)
