### ISSUE TITLE
Trigger validation

### ISSUE THREAD

**Issue by mintyPT** [react-tools/react-form#116]
Before the user as even done something, is it possible to trigger the validation?

**Comment by thg303** [comment]
@mintyPT That could be done with setting a **ref** on the `Form` component and call `SetAllTouched(true)` something like this:
```
<button onClick={() => this.refs.aForm.setAllTouched(true)}>validate now!</button>
<Form
ref="aForm"
 ...>
```

**Comment by mintyPT** [comment]
I tried. It calls the onChange but not the validation

**Comment by mintyPT** [comment]
It's a good suggestion. I tried it. Saldy, it calls the onChange but not the vlaidation

**Comment by joepuzzo** [comment]
@mintyPT  We are working on V2 of this lib and it will call validation when the form mounts! This way you can render errors right off the batt or if you chose to checked the touched field you can wait to show errors when touched. Side note: I will eventually make it so this is configurable via a prop so you as the developer can chose how it works.

**Comment by joepuzzo** [comment]
We have moved to V2 and this should work as expected. Let me know if you still have issues with the new stuff.
