### ISSUE TITLE
Validate as the user types

### ISSUE THREAD

**Issue by amaschas** [react-tools/react-form#117]
I've tried every variation of setting inputs touched, playing with onChange and noTouch, and I can't figure out how to get a form field to trigger validation as the user interacts with it. Is there a way to do this?

**Comment by joepuzzo** [comment]
hmm i thought this worked in the current version but i may be mistaken. Regardless we are working on getting V2 rolled out soon and i know this works in there. Its also a lot quicker :)

**Comment by joepuzzo** [comment]
V2.0.0 is now out. Closing unless you find its a problem in the new version.
