### ISSUE TITLE
Reverting to default values on rerender

### ISSUE THREAD

**Issue by onoufriosm** [react-tools/react-form#118]
Scenario: 
1. Form rendered with defaultValues.
2. User changes some fields.
3. User does something else (e.g. upload a profile picture) which is **not** part of the of the form (but part of the parent component that both the form and the upload profile picture components live) and causes a rerender of the form.
4. The form reverts back to the default values instead of persisting the changed values.

The problem arises at stage 4. The form should persist the new values instead of reverting back to the defaultValues. This problem doesn't happen if no default values are passed to the form. Any ideas?

**Comment by onoufriosm** [comment]
I managed to find a workaround by keeping the form values in the state of my parent component. This is not ideal but it works: 

```
  constructor (props) {
    super(props)
    this.state = {
      values: false
    }
    this.updateStateValues = this.updateStateValues.bind(this)
  }

  updateStateValues(data) {
    this.setState({
      values: data.values
    })
  }
 
  ....

  render () {
    ...
    <Form
        onSubmit={this.handleSubmit}
        defaultValues={this.state.values || myDefaultValues}
        onChange={this.updateStateValues}
    ...
    <ProfilePhoto .... />
```

If there is an alternative I'd be glad to hear it. Thanks.

**Comment by maxmatthews** [comment]
I've run into an issue where calling `setState` caused the form values to empty out. I came up with this solution: 
```js
onSubmit={(values, state, props, instance) => {
	this.setState({ dataToUpdate }, () => {
		instance.setAllValues(values);
	});
}}
```
You could access instance through refs as well. It's not ideal behavior, but it does fix the issue.

**Comment by amaschas** [comment]
Just create a PR for this. Looks like the Form component was updating incorrectly from props instead of state in some cases.

**Comment by bryandowning** [comment]
I hope that PR gets merged soon! I just ran into a similar problem where using `defaultValues` would cause the form to lose track of the state. Instead of using `defaultValues`, I used `loadState`:

```
<Form
  loadState={() => ({values: {...this.state.values}})}
  onChange={({values}) => this.setState({values: values})}
>
```

This is also mentioned in #61

**Comment by thg303** [comment]
nice one. hope someone shows up and handles PRs.

**Comment by amaschas** [comment]
@tannerlinsley do you know when you'll be able to take a look at this?

**Comment by joepuzzo** [comment]
@amaschas We are working on getting a V2 of react form out. V2 uses redux under the hood, and hopefully will solve this problem. As it stands, the V2 does not support setting the defaultValues ( had to focus on rebuilding the lib from the ground up first ) however i would be glad to add this functionality ASAP once we get the initial code published.

**Comment by joepuzzo** [comment]
@amaschas Scratch that.. i just added support to defaultValues to react-form V2 so you should be all set once we roll that out!!

**Comment by joepuzzo** [comment]
@amaschas just rolled out v2.0.0 maybe give this use case another go and see if it works. Note, This was a major update, so there will likely be some breaking changes.
