### ISSUE TITLE
NestedForm does not propagate values to parent form on submit

### ISSUE THREAD

**Issue by amaschas** [react-tools/react-form#119]
When using a NestedForm in this fashion:

```
<Form
  onSubmit={values => console.log(values)}
>
  <Text field='field1' />
  <NestedForm field='nestedForm'>

    {() => (
      <Form>
        <Text field='field2' />
      </Form>
    )}

  </NestedForm>
</Form>
```

The value of `nestedForm` is not defined in `values` object when the form is submitted.

**Comment by joepuzzo** [comment]
@amaschas Im not sure if this is a problem in the current version, will need to verify, but we are working on V2 of this lib and this is not an issue. Stay tuned :)

**Comment by joepuzzo** [comment]
React-Form is now at 2.0.0 and this is no longer an issue. Closing
