### ISSUE TITLE
Support `setAllTouched` or `setDirty`

### ISSUE THREAD

**Issue by aghreed** [react-tools/react-form#122]
First - thanks for your time and effort creating this library. I ran into a misunderstanding that cost me some development time that I think could be avoided in the future with some function renaming, or increased documentation.

I was under the impression that `setAllTouched` would set all the fields that I have in the form into a touched state. However, what this function really does is sets the `dirty` flag. I'd simply suggest that at the very least an alias method could be introduced (so as not to incur breaking changes) named `setDirty` that would more appropriately describe what that function does.

I do realize that the description under the method does describe that it set's dirty, however it wasn't clear to me the relationship between `dirty` and `touched` in the form state. So this might also be alleviated with some further documentation that describes the philosophy and approach taken. I'm thinking something that shortly explains the make up of the form's internal state (state, errors, touched, and dirty) and the role that each piece serves. Thoughts?

**Comment by joepuzzo** [comment]
V2 currently does not support the setAllTouched. I am planning on adding dirty and pristine flags soon to V2 and maybe also add setAllTouched.

**Comment by joepuzzo** [comment]
I have added setAllTouched... it has different signature than before.

**Comment by beausmith** [comment]
@joepuzzo - Are there still plans to implement `formApi.dirty` and/or `formApi.pristine`? 

I'd like to be able to enable/disable the form submit button based upon values changing, and not wait for an `onBlur` touched event.

**Comment by joepuzzo** [comment]
@beausmith Hey yeah sorry, a lot of other features have taken up my time... this should technically be a simple add i have just yet to put my brain on it lol. Its on the radar

**Comment by FredyC** [comment]
Is there some suggested workaround for now how to monitor changes in fields so I can notify a user when leaving a form that has modifications?
