### ISSUE TITLE
Update to React 16 

### ISSUE THREAD

**Issue by mykhailo-riabokon** [react-tools/react-form#124]
Hi,

As you probably know React was updated to version 16 (major version update). So, do you have somewhere in a roadmap dependencies update as well? In particular `peerDependencies` which says, react-form can work with `^15.3.1`? Thank you for any feedback.

**Comment by joepuzzo** [comment]
This is def something that will be coming down the road. Im working on V2 of this lib now and that will be in the roadmap.

**Comment by mykhailo-riabokon** [comment]
@joepuzzo please let me know if I can help you with something.

**Comment by joepuzzo** [comment]
@mykhailo-riabokon will do. Having just moved to V2 i want to make sure everything runs smoothly with React 15 first. Will keep u updated

**Comment by drusellers** [comment]
Outside of one odd issue, that I think is my own issue - its (v2) working quite nicely on React v16

**Comment by tannerlinsley** [comment]
Fixed in master. :) Yay!
