### ISSUE TITLE
Treating missing values as validation errors only when submitting

### ISSUE THREAD

**Issue by mnieber** [react-tools/react-form#126]
Hi, my validate function looks like this (simplified):

```
  _validate = ( {categoryId, answers}, state, props, instance ) => ({
      categoryId: !categoryId && 'The category field is required',
      answers: answers && this.answerField.validate(answers)
  })
````

The individual answer fields in my form are of type `Textarea` and have a `field` that looks like  `answers.${someKey}.answer`. This produces a hashmap of answers that is passed to the validate function (great!). Now, assume the following sequence of actions:

1. the user sets the `categoryId`, 
2. the `validate` function kicks in. Since the `answers` hashmap is empty, the answers are not validated. This is fine, since the user hasn't touched these fields.
3. the user submits the form
4. the `validate` function kicks in again. The `answers` hashmap is *still* empty, but now this should be a validation error, as the user is submitting the form without specifying the answers.

So it seems that the `validate` function must behave differently for "intermediate validation" than for "final validation on form submit". How to achieve this?

**Comment by joepuzzo** [comment]
Your answers should also have an error state for when its empty.
```
answers: !answers ? 'You must provide answers' : this.answerField.validate(answers)
```

**Comment by mnieber** [comment]
@joepuzzo Actually, this.answerField.validate(answers) also complains if `answers` is empty. The problem is however that in step 2 of my sequence, it's not yet an error if `answers` is empty (at this point in the sequence, I don't want to do *any* error checking on `answers` yet)

**Comment by tiagobnobrega** [comment]
I think you colud get around this using form API submitform [(submitform)](https://github.com/tannerlinsley/react-form#submitform-) to define some prop indicating the form is being submitted. Something like this.

```jsx
// Considering setFormSubmit a function that defines some variable to be retrived 
// by the validation function.

<Form
  onSubmit={(values, state, props) => {
    console.log(values)
  }}
>
  {({submitForm}) => {
    return (
      <form onSubmit={(...args)=>{ this.setFormSubmit(true); submitForm(args); this.setFormSubmit(false); } }>
        <button type='submit'>Submit Form</button>
      </form>
    )
  }}
</Form>
```
you will probably have to watch out for submitForm errors.

It seem kinda hacky solution, but it could work. Maybe you can achive this behaviour using some of the events. I don't know if the form api already does store a form submission attemp somehow. Anyway just an idea for a quick workaround.

PS: Code not tested.

**Comment by joepuzzo** [comment]
We have moved to V2 of react form. Try this in V2 and if you are still having issues open a new issue :)
