### ISSUE TITLE
Override the Classname

### ISSUE THREAD

**Issue by smks** [react-tools/react-form#127]
Our convention is lowercase, hyphened class names. But this library is rendering uppercase classes which is not desired. Is it possible to change this?

.FormInput {

}

I also cannot add classes to this div, which is very limited considering I want to apply different :after selectors to the div.

**Comment by joepuzzo** [comment]
You can always create your own custom Fields using the FormField. This is what i have done in the past to format and style them how i want. Also note, react-form V2 is almost ready and has docs that show you how to write these custom fields. Stay tuned :)

**Comment by joepuzzo** [comment]
V2 is ready and you can customize the fields however you like. Closing because we no longer add classes ourselves, it is now up to the dev to create there own inputs or pass styles to the default ones. See the example custom input in the docs.
