### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by mervintankw** [react-tools/react-form#128]
Hi, does this form supports server side validation? Like using promises or callbacks with form field validation.

**Comment by joepuzzo** [comment]
@mervintankw Work in progress! I am working on V2 of react-form and asynchronous validation is in it and working! Check out this url for sneak peak http://react-form.cfapps.io/#/

**Comment by mervintankw** [comment]
@joepuzzo Cool! Looking forward to using this library once asynchronous validation is in!
