### ISSUE TITLE
Error does not get overridden when you quickly change field during async validation.

### ISSUE THREAD

**Issue by joepuzzo** [react-tools/react-form#129]
Im aware of this issue and logged for traceability. 

To recreate: 
1. Go to the async form example in the documentation
2. type "joe" and tab out of field
3. very quickly go back into field and ad a "d" after "joe"

Result: the field will think its in an error state from typing "joe" first.

Currently typing anything in field fixes this issue but thats not acceptable.. will work soon.

**Comment by thg303** [comment]
I think it would be great if somebody show up and handle PRs. some of them **maybe** fix some unreported issues.

**Comment by joepuzzo** [comment]
@thg303 We just moved to v2 so the pull requests are now way to out of date. Many of the issues have been fixed in V2 and I would be happy to work with future pull requests.

**Comment by tannerlinsley** [comment]
As far as I can tell, this is fixed in 2.0 :) Huzzah!

**Comment by joepuzzo** [comment]
Fixed in V3!
