### ISSUE TITLE
Form validation on mount

### ISSUE THREAD

**Issue by KarpovNik** [react-tools/react-form#130]
Hi everyone.
Is it possible to disable validation when the form mounts?
V2

**Comment by joepuzzo** [comment]
Form validation occurs by default when the form mounts in V2.

**Comment by KarpovNik** [comment]
So there is no way to prevent this behaviour?

**Comment by joepuzzo** [comment]
Not right now but i am looking to add a prop to disable this. I can look into adding this prop today and get back to you! Validating on mount by default had more pros than cons and solved some other complexities that i have to revisit to allow this functionality.

**Comment by joepuzzo** [comment]
In the mean time however, if you need to prevent errors or something from showing up just used the touched attribute.

**Comment by joepuzzo** [comment]
@KarpovNik I have added a `dontValidateOnMount` flag! Its in V2.0.3 so grab @latest and see docs for ref
