### ISSUE TITLE
how to use input type="file"?

### ISSUE THREAD

**Issue by wayne5540** [react-tools/react-form#149]
First if all, thanks for the hard work, this project amazing.

However I'm wondering how to add a file input tag to react-form, for example:

```html
<input name="message[attachment]" accept="image/jpeg, image/png" type="file" />
```
I expect this input to encode base64 data as value so I can send it to my API endpoint.

Any hint?

Thanks.

**Comment by joepuzzo** [comment]
Hey @wayne5540. So i have no default ( out of the box ) `FormFields` that support files ATM. BUT you can very easily create a custom Input via the `FormField`. Check out the docs here https://react-form.js.org/#/custom-input.

**Comment by joepuzzo** [comment]
@wayne5540 any updates on this? Have you tried to create a custom input

**Comment by wayne5540** [comment]
Hi @joepuzzo thanks for following up 😄  

I ended up using [react-dropzone](https://github.com/react-dropzone/react-dropzone) and native react form to create my FileInput. Since my form is quite simple so it's not necessary to use plugin to create my form. However react-form is an awesome plugin, I'll definitely try it in the near future when my form becomes more complex than now 😸 

close this issue.
