### ISSUE TITLE
how to set the text values when the form is first loaded?

### ISSUE THREAD

**Issue by lynnchin** [react-tools/react-form#151]
Do you have an example that shows us how to set the text value when the form is loaded?  I tried with something like this ``` <Text field="name" id="name" value={this.state.value} /> ``` but it's not working.

**Comment by lynnchin** [comment]
It appears that I found there is a way to set the value before loading the form. Basically I just use getApi props in the Form component level to set the value with the text field and id called 'hello-field' in the FormContent component.
```
const FormContent = ({ formApi }) => {
	return (<form onSubmit={formApi.submitForm} id="form1" className="mb-4">
          <label htmlFor="hello">Hello World</label>
          <Text field="hello" id="hello" />
          <button type="submit" className="btn btn-primary">Submit</button>
    </form>)
  };

<Form getApi={(formApi) => { formApi.setValue('hello','default value') }}>
		    <FormContent />
	     </Form>
```

Would like to see if there is any other better ways on doing this.

**Comment by joepuzzo** [comment]
Look at the docs and see the default values prop. Or u can also use the set value like you have done above

**Comment by lynnchin** [comment]
I see. Well, I was thinking if default values is the appropriate way to do this. What I was trying to do is to make an API call and set the value in text field when successful response is returned. Default values seems to be used in a situation where the values are already known when rendering the component.  

Anyway, thanks for the suggestion!

**Comment by joepuzzo** [comment]
So there are two options for what u need. Option 1: if you can make your API call before you render your form, then use default values. Option 2: if your api call needs to happen after the form has been rendered, use setValue. This is actually perfect example of when to use set value.
