### ISSUE TITLE
Nested forms overwrite values passed to addValue

### ISSUE THREAD

**Issue by casperOne** [react-tools/react-form#152]
This is with the latest version (at this time), 2.4.0.

When using nested forms, it assumes that there aren't prior values that exist in the form at the location that it's mounted to.

See the following sandbox:

https://codesandbox.io/s/vqo5054xy0

When the `Add Child` button is clicked, it calls `addValue` and renders out the children.

If I use a `Text` control with the `field` set to the full path, everything works fine.

However, if I use a nested form, it isn't aware of the value that was added in the call to `addValue` and overwrites the entire object once I start to mutate the value in the nested form.

**Comment by joepuzzo** [comment]
Right this is somthing i should call out in docs.. react-form does not support using addValue where the new value results in a nested formField. Add value is supposed to be used to add basic fields to a form, OR nested form. I think you have two options here. 1 - do what you are doing now and use the full path. 2 - If you want the children to be nested forms ( I would probably want this ) then have your AddValue button simply render another nested form dynamically. In other words you wont be looping over `values.children`, but instead the amount of children you have added. 

Side note: You have two nested forms in your example -
```
<td>
      <NestedForm field={['children', index]}>
        <Form>
          {
            api =>
              <div>
                <Text field='childId' />
              </div>
          }
        </Form>
      </NestedForm>
    </td>
    <td>
      <NestedForm field={['children', index]}>
        <Form>
          {
            api =>
              <div>
                <Text field='description' />
              </div>
          }
        </Form>
      </NestedForm>
    </td>
```

This is slightly off. What you really want is this: 

```
 <NestedForm field={['children', index]}>
        <Form>
          {
            api =>
              <div>
              <td>
                <div>
                  <Text field='childId' />
                </div>
              </td>
              <td>
                <div>
                  <Text field='description' />
                </div>
              </td>
            </div>
          }
        </Form>
      </NestedForm>
```

You will have to play with style to get the table to look good.

**Comment by joepuzzo** [comment]
@casperOne can i will be closing this unless there is more to discuss?

**Comment by casperOne** [comment]
@joepuzzo Yes, feel free to close this.

Also, the double `NestedForm` was intentional, only to get the table to space correctly.

I have a generic solution to track object paths in a hierarchy which I used with `redux-form`, which was easily adapted for this purpose.
