### ISSUE TITLE
FormField not rerendering after async validator returns

### ISSUE THREAD

**Issue by simonrobb** [react-tools/react-form#156]
I have a custom input with an async validator. Upon the async validator returning an object `{ error: 'Error message' }`, the `<Form />` component correctly receives the new error however the `<FormField />` does not rerender - hence the error message isn't displayed until the control is refocussed and edited.

I've traced the problem to the `shouldComponentRender` method in the `FormField` HOC. Upon the validator returning, the method is invoked twice: first with `this.context.formApi.errors` and `nextContext.formApi.errors` both undefined, and second with both equal to the new error. Because they are always the same, the comparison `shouldUpdate` is always `false` and the `render` method is never called.

Being unfamiliar with the codebase I couldn't work out why this was happening, but maybe you can shed some light.

**Comment by joepuzzo** [comment]
Hmm you're right.. i will look into this.

**Comment by joepuzzo** [comment]
@simonrobb Ok so i put in a fix that will now make this work.. not the fix i would like but it will work. Basically i added a check to see if the `validating` object changed signifying that the field was done validating. I need to keep looking into why the error was the same but can you let me know if that worked?

**Comment by simonrobb** [comment]
Thanks for the quick fix! Yes can confirm issue is fixed in 2.6.1.
