### ISSUE TITLE
Can't find onValidationFail in react-form v2

### ISSUE THREAD

**Issue by jiangweiliu-aa** [react-tools/react-form#158]
Currently, I'm upgrading react-form from v1 to v2. I haven't found `onValidationFail` which is prop of `Form` supported by v2.

Is there workaround for replacing `onValidationFail`?

**Comment by joepuzzo** [comment]
Yeah my apologies as there are a few features i have yet to port over. I can look into adding this.

**Comment by jiangweiliu-aa** [comment]
Thanks for your inform, this function actually is very useful. Without this function, my workaround is: 

After all validation check in function `validateError`, I will check if there is any error value, if there is, it will run the function `onValidationFail`.

Which is quite dirty! 

It is reasonable that dev can do something during each step in a validation cycle, just like `preValidate`.

I'm hoping that it will be provided.

**Comment by joepuzzo** [comment]
hmm my only issue with adding this is i would basically have to do your workaround internally... the issue with that solution is i would have to "look" at the errors object every time validation occurs and validation occurs every time you type in a text input... there will most likely be performance issues here.

**Comment by joepuzzo** [comment]
I think a better solution that will take more time to implement is to increment and decrement a value for every error that exists. This way i would not have to parse the errors object every time but instead check an integer.

**Comment by jiangweiliu-aa** [comment]
got your meaning. Thanks! Currently, my workaround works well, even it is dirty, so that I don't need a hotfix for it but a long term excellent design for it. I think this is better for both the library itself and my project.

**Comment by sboudrias-aa** [comment]
> i would have to "look" at the errors object every time validation occurs and validation occurs every time you type in a text input

I might be wrong, but I think `onValidationFail` was only triggered when form submit was aborted due to validation error no?

**Comment by joepuzzo** [comment]
@sboudrias-aa Oh this might be the case.. if it is then i can def add that... maybe call it onSubmitFailure or somthing so its more clear?

**Comment by SBoudrias** [comment]
This would work for us :)

**Comment by joepuzzo** [comment]
Added `onSubmitFailure` in V2.10.0

**Comment by jiangweiliu-aa** [comment]
Cool, thank you very much!
