### ISSUE TITLE
What is the motivation of using Redux for v2?

### ISSUE THREAD

**Issue by SBoudrias** [react-tools/react-form#159]
Hi, I searched for an answer, but couldn't find any on the website/documentation or changelog.

What was the motivation to add all those new dependencies on redux in v2?

React form v1 was pretty lightweight, but now it's a bit more complex.

**Comment by joepuzzo** [comment]
Create an old react-form from V1 and add more than 6 inputs. Now open it in internet Explorer and watch as you type and the letters show up seconds after you type them lol. 

This is one of the motivations but mainly using `state` is very slow and cumbersome. Redux solves this problem and makes the code much simpler, stable, and more consumable with an emphasis on stable. Remember that react batches state updates which can lead to many issues. Redux has the nice property of having garnered synchronous updates.

**Comment by joepuzzo** [comment]
The cool part is that fact that it uses redux is abstracted away from the dev... other than noticing that it has it as dependency lol.

**Comment by joepuzzo** [comment]
@SBoudrias Are you cool if i close this as its not really an issue?

**Comment by SBoudrias** [comment]
@joepuzzo yes thanks for the answer.

I think you should state this clearly in the README though as it can have a bundle size impact on project not relying on redux. Or maybe just a 2.x release announcement post explaining the changes and motivation.

**Comment by joepuzzo** [comment]
@SBoudrias Agreed i can probs add some info about this somewhere. Thanks
