### ISSUE TITLE
"field" not passed to custom input from FormField

### ISSUE THREAD

**Issue by LyhjeHylje** [react-tools/react-form#160]
I have made a custom input that relies on the "field" -prop in v1. 
When converting to v2 I noticed that the FormField-hoc does not pass"field" to my custom input.

**Comment by joepuzzo** [comment]
There is a pull request for this. i will add it in the next release.

**Comment by joepuzzo** [comment]
https://github.com/react-tools/react-form/pull/154

**Comment by joepuzzo** [comment]
Working on this now stand by.

**Comment by joepuzzo** [comment]
Ok so i merged the pull request and added some docs... you now have access to  `fieldApi.getFieldName()`! https://react-form.js.org/#/custom-input . This is in latest version 2.7.0
