### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by nganlamsong** [react-tools/react-form#162]
Very good job you have, react-form is the one I chose for my project because of its simple and flexible ability!
Certainly, I'm having an issue when I try to create a custom input, I just simply copy the sample code from https://react-form.js.org/#/custom-input to my code and Webpack failed to compile with: 'classCallCheck.js:7 Uncaught TypeError: Cannot call a class as a function'

Any help for me?
Thank in advanced!

**Comment by joepuzzo** [comment]
This is not an issue with react-form. You might be missing a loader or babel setting for webpack, or maybe have something missing from your react project. You can see the code copied directly from the docs here https://codesandbox.io/s/r44op4kxp4.
