### ISSUE TITLE
`preSubmit` for v2?

### ISSUE THREAD

**Issue by hnq90** [react-tools/react-form#163]
I'm migrating my project from using `react-form` v1 to v2.
In old forms, I used `preSubmit` for normalizing form's values but in v2, it hasn't implemented yet.

So how can I implement `preSubmit` on v2? Is it good when call my normalization function in `submitForm`?

**Comment by LyhjeHylje** [comment]
I left my old v1 presubmit function as a class method and then did:
```
<Form
  onSubmit={values => {
      onSubmit(this.preSubmit(values));
   }}
 >
```
This is probably quite like what you are suggesting. It seems to work fine for me.
Having a preSubmit in react-form itself would be less confusing looking though.

**Comment by hnq90** [comment]
@LyhjeHylje Yes, actually I did same as yours but it's still better to have both `postSubmit` & `preSubmit` in react-form lifecycle.

**Comment by joepuzzo** [comment]
Yeah i can add these. I will keep ya posted

**Comment by joepuzzo** [comment]
I will probs only add `preSubmit`since you can just call a function in the onSubmit to achieve `postSubmit`

**Comment by joepuzzo** [comment]
Done!!! V2.9.0

**Comment by hnq90** [comment]
@joepuzzo Thank you for your hard work.
