### ISSUE TITLE
resetAll doesn't reset value to initial value

### ISSUE THREAD

**Issue by jiangweiliu-aa** [react-tools/react-form#164]
once I upgraded to react-form v2, `resetAll` doesnt' work like initial behavior, instead of resetting value to initial value, it reset value to an empty object `{}`

**Comment by LyhjeHylje** [comment]
Same here, although I have to call setAllValues to populate my form so I am unsure if that counts as initial values or not.

**Comment by jiangweiliu-aa** [comment]
@LyhjeHylje I tried `setAllValues ` as well, however, it won't reset touched status, so that even it has been reset to initial value, touched won't be reseted.

**Comment by joepuzzo** [comment]
Yeah resetAll will basically reset the form to the default redux state internally. Clearing out ( resetting ) anything that you have done. ‘DefaultValues’ is used to set forms initial values but it will be overridden by reset. Simply call setAllValues after calling reset and you should be ok.

**Comment by joepuzzo** [comment]
Are we cool to close this as resetValue does what its supposed to and you can achieve your use case other ways?

**Comment by LyhjeHylje** [comment]
I'll try just using setAllValues as described 2 posts ago. 

Though it sounds to me that resetAll is actually clearAll if it overrides 'DefaultValues'? (which I don't know how to set btw)

**Comment by joepuzzo** [comment]
https://react-form.js.org/#/ The docs describe how to use default values.

**Comment by joepuzzo** [comment]
And good point... default values could maybe be kept around when calling resetAll.

**Comment by sboudrias-aa** [comment]
Yeah, I don't really see the use case to clear everything. When would we actually want to do that rather than reset the form to the initial state?

**Comment by jiangweiliu-aa** [comment]
@joepuzzo Thanks for your update. 
it makes sense that rollback to default value while calling `resetAll`.

**Comment by joepuzzo** [comment]
Yeah @sboudrias-aa @jiangweiliu-aa I agree now that i think this was a miss when i added resetAll.. I will prob try and update to keep default values and add a `clearAll` as well.

**Comment by joepuzzo** [comment]
I have updated this in V2.9.1. ResetAll will now keep default values and I have also added `clearAll`
