### ISSUE TITLE
How to bind a list of options into Select field component with data returning from asynchronous call?

### ISSUE THREAD

**Issue by lynnchin** [react-tools/react-form#166]
Hi, I want to bind the list of options values by fetching data asynchronously from API call. I wonder how can I achieve this since the select component does not allow an empty list?

```<Select field="field-name" id="field-id" options={{}} />```

**Comment by joepuzzo** [comment]
Hmm i could maybe undate the select to support this but in the mean time just create a custom input using FormField.

**Comment by hnq90** [comment]
@lynnchin Pass an empty object to `options` will not work. I think it should be an array.
Or you could fill a default option for the form's initiation: `[{ label: 'Please select', value: '' }]`.

**Comment by joepuzzo** [comment]
Yeah there are probably a few ways you could do this. I would def try to mock out a custom FormField. Basically copy the source code for the default select and modify to fit your needs

**Comment by lynnchin** [comment]
yep @hnq90 I was having the issue if I pass in an empty object and it's not working at all, but it appears the way you suggest works fine :) Thanks guys! 👍
