### ISSUE TITLE
[Docs] Sidebar doesn't respond to mobile screen sizes

### ISSUE THREAD

**Issue by SebastiaanNijland** [react-tools/react-form#173]
Reproducible by resizing chrome to ~500px width. I suggest implementing the standard bootstrap navigation toggler: https://getbootstrap.com/docs/4.0/components/navbar/#toggler

**Comment by joepuzzo** [comment]
Yeah i am aware of this.. was low priority because i figured most devs dont look at code documentation on mobile.. that being said i def want to fix this eventually.

**Comment by dzienisz** [comment]
Do you have some TODO list what to change in DOCS? It would be easier for community to fix it.

**Comment by joepuzzo** [comment]
Ha yeah i have a bunch of things in mind. Need to take the time to sit down and bang them out.. that being said i could create a list under the better docs issue

**Comment by SebastiaanNijland** [comment]
Or create separate issues for various list items :) makes it easier to pick up

**Comment by dzienisz** [comment]
> Ha yeah i have a bunch of things in mind. Need to take the time to sit down and bang them out.. that being said i could create a list under the better docs issue

Don't put too much on your shoulder> thrust me I've been there :) it's better to delegate tasks if you don't have time to do something by yourself.

**Comment by joepuzzo** [comment]
Haha ok yeah i will start creating some issues then

**Comment by joepuzzo** [comment]
It does now but we will be working to improve the docs more soon.
