### ISSUE TITLE
Mobile Chrome/Safari autofill

### ISSUE THREAD

**Issue by sepowitz** [react-tools/react-form#174]
I realize this is a larger issue within the frontend community regarding how to handle browser autofill, but I was wondering if anyone has come up with a good way to handle it with redux-form.

**Comment by joepuzzo** [comment]
Could you provide more context?  My understanding is that browser autofill occurs when the browser, for example, sees a text input with `type=password` and tires to suggest your password. I don't think that this has anything to dow with the way `react-form` is implemented.

**Comment by joepuzzo** [comment]
Any updates on this? i will be closing if there is no further discussion to be had.

**Comment by sepowitz** [comment]
Feel free to close this out. I found a workaround.

**Comment by joepuzzo** [comment]
Cool thanks.
