### ISSUE TITLE
Possibility of Supporting setTouchedError?

### ISSUE THREAD

**Issue by jiangweiliu-aa** [react-tools/react-form#175]
I refer to https://github.com/react-tools/react-form/issues/100. 
The solution for it is using `FormField` to combine logic for showing error.

In our case, that we have so many places to wrap field to a FormField, because of using `FormField`. That is so expensive.

Besides, `setTouchedError` is really a good and strong required interface. Every time, when we create a form, showing error without being touched is a very bad user experience. So that as a `react-form` dev, we need to  implement `getTouchedError` for even every custom `FormField`.
That is also waste dev's time.

Three lines code will save everybody's life.
```
getTouchedError = (field) => {
      if (Utils.get( this.props.formState.touched, field )) {
          return Utils.get( this.errors, field );
      }
      return undefined;
  }
```
Hope that can be implemented.

**Comment by joepuzzo** [comment]
Create a PR lol. And it loons like you want getTouchedError.. not setTouchedError.

**Comment by joepuzzo** [comment]
And also saying ‘if( error && tocued )’ does not seen like a waste of devs time... i have that tiny if statement in my custom inputs to only show error after the field as been touched. In fact there is actually one other thing that i have ‘if( error && value )’ that will make it so errors only show if you have interacted with field.

**Comment by tannerlinsley** [comment]
I don't think this is necessary.  You could easily implement your own helper and use it wherever you would reference `..., getError, getTouched, ...` from the formApi.  `react-form`'s goal is not to cover every edge case or situation, but instead supply a reliable and flexible api to achieve solutions for said edge cases.

**Comment by joepuzzo** [comment]
I agree with @tannerlinsley .. if we started adding a helper getter for every permutation, things would get crazy. things like `getErrorTouchedValue` haha

**Comment by joepuzzo** [comment]
Closing as we don't want to implement permutations of getters in the lib.
