### ISSUE TITLE
How to setValue in array of NestedForms

### ISSUE THREAD

**Issue by LyhjeHylje** [react-tools/react-form#176]
I can't figure out how to call setValue from inside of array of nested forms
I have tried: 
setValue( "things[3].someproperty", somevalue )
setValue( "things.[3].someproperty", somevalue )
setValue( ["things", 3, "someproperty"], somevalue )
setValue( somevalue )
and all kind of variations of above. I tried to debug into setValue itself to see how it operates but that does not work for some reason.

**Comment by joepuzzo** [comment]
You need to call set values on the nested form... the second you use a nested form you have a separate instance of a formApi that is scoped to that nested form. This is very powerful for many reasons but it does prevent your use case. If you really want to do this, i would not use a nested form.

**Comment by LyhjeHylje** [comment]
Sorry, I should have been more specific: I have array of items that are shown in nested form, item properties are shown by a custom component. In that custom component's onChange method I'd have to somehow set the value. 

I first tried just "setValue(newValue)" but that messed the item's values all wrong.

I am also little bit unsure if I should but my array of items inside nestedform or render an array of nestedforms, currently I am using the latter and can show items but not change them

**Comment by joepuzzo** [comment]
Can i see the source for ur custom input? And i typically use nested forms when i want to encapsulate validation and functionality. If you dont have that need then u dont need nested forms.

**Comment by LyhjeHylje** [comment]
With fresh brain and lot of testing I finally got it working, although I now have problems with removing values from array. 

Only the last item can be actually removed and when I try to submit form after removing, there appears an extra property in the values:
E.g after removing last item values is { myItems:[...], "item,1": null}

I realise the remove-problem might be because I have knead my code so much back-and forth and created an overly complex setup. I might have also used NestedForm completely wrong.

```javascript
class MyForm extends React.Component {
    render() {
        const values = {
            myItems: [{ id: 0, name: "A" }, { id: 1, name: "B" }],
            someOtherProp: "abc"
        };
        return (
            <Form defaultValues={values}>
                {formApi => (
                    <form onSubmit={formApi.submitForm}>
                        <ItemList formApi={formApi} field={"myItems"} />
                    </form>
                )}
            </Form>
        );
    }
}

class ItemList extends React.Component {
    render() {
        const { field, formApi: { values = {} } } = this.props;
        const items = values[field] || [];
        return (
            <div>
                {items.map((item, i) => {
                    return (
                        <NestedForm field={[field, i]}>
                            <Form defaultValues={item}>
                                {innerFormApi => (
                                    <div>
                                        <CustomSelect field={"name"} />
                                        <button
                                            onClick={() => {
                                                const existingId = items.findIndex( i => i.id === item.id );
                                                this.props.formApi.removeValue(
                                                    this.props.field,
                                                    existingId
                                                );
                                            }}
                                        >REMOVE</button>
                                    </div>
                                )}
                            </Form>
                        </NestedForm>
                    );
                })}
                <button
                    onClick={() => {
                        this.props.formApi.addValue(field, { id: null,name: "" });
                    }}
                >ADD</button>
            </div>
        );
    }
}

class CustomSelect extends React.Component {
    render() {
        const { fieldApi } = this.props;
        const { getValue, setValue, setTouched } = fieldApi;
        const field = fieldApi.getFieldName();
        return (
            <ReactSelect
                field={field}
                value={getValue()}
                onChange={selection => {setValue(selection ? selection.value : null); }}
            />
        );
    }
}
```

**Comment by joepuzzo** [comment]
Hmm yeah im not sure It works in the basic case so i think your guess is correct about having a complex use case... I would try breaking the problem down smaller to determine whats going on

**Comment by joepuzzo** [comment]
Closing this as its not an issue with the lib. For further discussion please go on https://react-tools.slack.com/messages/C3TM660JV/

**Comment by LyhjeHylje** [comment]
Finally got it working by getting rid of nestedforms. Here's working example in case someone else wants to do lists with custom components.
https://codesandbox.io/s/1vxl4pyvml
