### ISSUE TITLE
Is there a way to get all form values, even if they haven't been changed.

### ISSUE THREAD

**Issue by finppp** [react-tools/react-form#177]
When I get all the values from a form even if they haven't been changed?

e.g. using the example found [here](https://react-form.js.org/#/basic-form) (the basic form)

When the user clicks submit without changing any of the fields, the `Values:` returns an empty object.
Is it possible to get each value even if it is an empty string, or a false checkbox?

Thanks,
Fin

**Comment by joepuzzo** [comment]
By default the values is empty until you interact with field.. if you want to set fields to things like empty strings `''` or an unchecked checkbox then use the `defaultValues` to initialize them.

**Comment by finppp** [comment]
Are there any examples of this being done? I couldn't find any in the docs.

Thanks

**Comment by joepuzzo** [comment]
The docs describe how to use it in the intro section under form props

**Comment by joepuzzo** [comment]
Closing this as the solution described above will allow you to pre-fill the values.

**Comment by finppp** [comment]
Where does this `defaultValues` object go?

**Comment by finppp** [comment]
Got it working. Thanks!

I was confused about where to put the `defaultValues` object

**Comment by joepuzzo** [comment]
Oh haha thats fine.. the section in the docs labeled “Form Props” shows all props that you can put on the Form component
