### ISSUE TITLE
subString not defined when using FormField

### ISSUE THREAD

**Issue by casperOne** [react-tools/react-form#180]
Version:  2.12.0

https://github.com/react-tools/react-form/blob/50dfbf0a0f74c3627dca7918838f72d4a1cf22f8/src/redux/utils.js#L37

I believe this is a typo when using `FormField`; it is trying to get the `substring` of a string, but uses `subString` which causes an exception to be thrown when using `FormField`.

**Comment by joepuzzo** [comment]
Woops.. fixed this in 2.12.1
