### ISSUE TITLE
Better documentation, please!

### ISSUE THREAD

**Issue by tiffwu** [react-tools/react-form#181]
Trying to get started with react-form and I find the documentation lacking. It'd be great to get at least the high level component API documented -- for example, what is a RadioGroup? Why would I use it instead of (or in addition to) Radio?

**Comment by joepuzzo** [comment]
Ha yeah i know there are a few things that i need to still document better. Radios are typically generally not used independently. They exist as a group where you select one of them. So the radio group is the wrapper around radios that provides the group to each radio. There are technical reason fo implementing it this way. But again i agree i need to talk about it in the docs.

**Comment by dzienisz** [comment]
You should also add "password" <Text> field into documentation.

**Comment by joepuzzo** [comment]
Just pass in type=password to the Text input

**Comment by wilomgfx** [comment]
@joepuzzo  yes but that should be said in the docs haha. <<Text input >> does not make explicit that we can pass the type attribute.

**Comment by wilomgfx** [comment]
@joepuzzo Also how do we get out Radio buttons to be checked ? Can't seem to figure it out when using RadioGroup

**Comment by captDaylight** [comment]
I see a update I want to make on the documentation, where is the repo?

**Comment by joepuzzo** [comment]
Its under /dev.. eventually need to reorganize the dirs

**Comment by janat08** [comment]
how to implement custom radios and selects?

**Comment by joepuzzo** [comment]
Radio groups are no longer a thing in V3 and also i updated the docs to have an inputs section!
