### ISSUE TITLE
Documentation and examples on how to send the form data to the backend!

### ISSUE THREAD

**Issue by joelmenezes** [react-tools/react-form#182]
All the documentation currently focuses on what to do with the form. There is nothing about how to POST requests to the back-end.

**Comment by joepuzzo** [comment]
This is because the documentation is for the form lib.. and not for how to make REST calls. That is outside the scope of the lib.

**Comment by darrenbarklie** [comment]
I came here looking for the same thing, as I am continuing to learn React.  I can appreciate limiting your documentation scope, but submitting data to an API must be considered at least worthy of at least a single sample.

Could someone support with a sample of how to send data collected by `formApi.submitForm` to `action="api/contact" method="post"`?

My newbie understanding is that adding the action/method props to the `<form>` element would suffice, as documented [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms).
