### ISSUE TITLE
App breaks with "Uncaught TypeError: n is not a function" when compiled with uglifyJS

### ISSUE THREAD

**Issue by danbopes** [react-tools/react-form#185]
Trying to track down an issue, and I've tracked it down to react-form. When I attempt to include react-form and run UglifyJS with mangle = true, the entire build breaks.

Reproduce via repository here: https://github.com/danbopes/webpack-uglify-react-form-issue

Compile with:
$ yarn
$ webpack -p

Open public/index.html in your browser (No need to run any webserver). Simply set `mangle: false` in webpack.config.js or remove `import { Form, Text } from 'react-form';` from src/index.jsx, and the app compiles correctly.

![](https://i.imgur.com/TPr1GDL.png)

**Comment by joepuzzo** [comment]
Hmm this sounds like an issue with your setup. Not with react form.

**Comment by danbopes** [comment]
This is likely caused by using functions that refer to constructor names, where mangling isn't possible. This is either an intended issue (Which I would recommend we modify/workaround to solve this issue), a bug in react-form's code, or an uglify-js issue. Since this issue has only cropped up after adding react-form, I thought the recommended route should be to post here first.

**Comment by SebastiaanNijland** [comment]
We ran into this issue as well. In our setup, we had a conflict between uglify-js, webpacks -p flag and react-form. It worked fine until updating to react-form 2.x.x

**Comment by joepuzzo** [comment]
Can you explain functions that refer to constructor names @danbopes

**Comment by danbopes** [comment]
I'll dig into this more tonight, and I'll follow back to see if I can diagnose/solve the issue.

**Comment by danbopes** [comment]
After further digging, it appears it's dying on one of the require() lines. `require("babel-runtime/helpers/extends")` to be specific. It may have something to do with webpack-node-externals, and I'll be looking more into this today.

**Comment by joepuzzo** [comment]
Any updates on this. Sorry i have been at a conference all week and have not had a chance to dig into many issues this week.

**Comment by danbopes** [comment]
Right now, waiting to hear back from the guys from uglifyjs-webpack-plugin. It appears as it may be an uglifyjs issue.

**Comment by joepuzzo** [comment]
Ok cool. Thanks for looking into this.  And keep me posted 😁

**Comment by kzc** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/179#issuecomment-349136025
