### ISSUE TITLE
Select doesn't work on IE11

### ISSUE THREAD

**Issue by slaby93** [react-tools/react-form#186]
When I use ```Select``` element on IE11 I receive:
```Object doesn't support property or method 'findIndex'```
I used IE11 from browserstack ( latest ).
In IE11 there is no https://github.com/paulmillr/Array.prototype.findIndex

**Comment by joepuzzo** [comment]
I will look at this when i get a chance.

**Comment by mrmedina87** [comment]
Hello! @joepuzzo Did you start with some kind of fix for this issue??

Thanks!

**Comment by joepuzzo** [comment]
I will get to it soon. I have been at conference all week anc have not had a chance to get to it.

**Comment by joepuzzo** [comment]
Sorry it has taken so long im going to look into this now!

**Comment by joepuzzo** [comment]
This works now in the latest version!
