### ISSUE TITLE
Masking input

### ISSUE THREAD

**Issue by dzienisz** [react-tools/react-form#187]
Is there any way to make mask on input?

Like phone numer mask: 123 123 123

**Comment by joepuzzo** [comment]
Try using prevalidate

**Comment by dzienisz** [comment]
hmm do you plan to implement this into react-form?

**Comment by joepuzzo** [comment]
Implement what exactly? A phone field ?

**Comment by joepuzzo** [comment]
Any updates on this.. or can I close?
