### ISSUE TITLE
Formation of validateError return object when validating arrays?

### ISSUE THREAD

**Issue by LyhjeHylje** [react-tools/react-form#188]
I need to validate 
```javascript
values = {
   bunchOfItems: [
      {name:"A"},
      {name:"B"},
      {name:null}
   ]
}
```
I'd expect that I should return object like this:
```javascript
{
bunchOfItems: [
      {},
      {},
      {name:"Name required"}
   ]
}
```
But that does not work.
I can validate non-array fields so otherwise my code should be ok. 
Do I really have to set all the passing fields to "null" like in documentation? When validating simple fields I only set the failing field and that does work.

**Comment by joepuzzo** [comment]
As it stands if you have set an error it sticks around until you override it with null

**Comment by LyhjeHylje** [comment]
Currently I cannot even set an error on item that is inside an array. I have to validate a lot of similar items with same fields so I suspect that the error object also has to be an array and the array index should correspond to the actual items?

Setting null to clear sounds reasonable though.

**Comment by joepuzzo** [comment]
Hmm i set errors on things in array all the time. Could you show me your validator

**Comment by joepuzzo** [comment]
And after rereading your last comment yes you would need an array that would look like the following for example: 
```
[ null, 'error', 'error', null, 'error' ]
```

**Comment by LyhjeHylje** [comment]
Now I feel stupid; I had made a custom component but not implemented the "show error message" on that so of course I saw nothing. :flushed:
Sorry for taking your time
