### ISSUE TITLE
How to detect in validateError that the form is about to be submitted?

### ISSUE THREAD

**Issue by mnieber** [react-tools/react-form#190]
I would like to use this information to show certain field errors only when submitting the form (not while the user is still filling out the form). I'm using version 2.12.2.

**Comment by joepuzzo** [comment]
Use the submits value in the form api

**Comment by mnieber** [comment]
Thanks for the suggestion, I overlooked this property. 

I'm now using `getApi` to obtain a reference to `formApi`, so I can call `formApi.getFormState().submits` inside `validateError`. However, it seems this counter is only increased after the form was really submitted, so it can't be used to detect in `validateError` that the form is about to be submitted.

**Comment by joepuzzo** [comment]
So “submitted” is set to true when form is successfully submitted. “Submits” is incrimented when form attempts to submit. Even when validation fails so u should be all set

**Comment by akshayKrSingh** [comment]
how can I use `getApi` inside validateError function ?

**Comment by joepuzzo** [comment]
Any updates on this?

**Comment by mnieber** [comment]
Sorry, for me it did not work like you described: formApi.getFormState().submits is only increased when `onSubmit` was actually called, so checking this value in validateError (which of course runs before onSubmit) does not help. I can try this experiment again, but this is what I found the last time.

**Comment by joepuzzo** [comment]
Ahh i see now what u need. Hmmm. So u almost want a submitting value on the form api

**Comment by mnieber** [comment]
Yes, I guess that's what I need :-)

**Comment by joepuzzo** [comment]
I think i can add this

**Comment by joepuzzo** [comment]
Done! This is in the latest version. See docs for details on new submitting value on formApi!
