### ISSUE TITLE
submitForm never passes event to this.finishSubmission, so event in onSubmit is undefined.

### ISSUE THREAD

**Issue by danbopes** [react-tools/react-form#191]
See: https://github.com/react-tools/react-form/blob/master/src/components/ReduxForm.js#L360

`this.finishSubmission()` should be `this.finishSubmission(e)`.

**Comment by joepuzzo** [comment]
Good Catch! i will put out a patch right away.

**Comment by joepuzzo** [comment]
Fixed in latest release!
