### ISSUE TITLE
Add a group of five dynamic fields on button click

### ISSUE THREAD

**Issue by fsolar** [react-tools/react-form#192]
Hi, im working with react-form and it's all ok but i need to dynamicly add a group of five inputs on every "Add" button click, same code as the examples work well with one field but i can't figure it out how to add dynamicly more than one input field.

**Comment by aivils** [comment]
Pass a object as value

```
  newTimeSlot() {
    return { week_day: this.props.day, from: '09:00', till: '17:00' };
  }

  this.props.formApi.addValue(['days', this.props.index, 'working_time_slots'], newTimeSlot());
```

In the time slot component
```
this.slotField = ['days', this.props.dayIndex, 'working_time_slots', this.props.index];

<StyledSelect field={this.slotField.concat('from')} />
```

Above works for me. <NestedForm> never fill initial values of siblings.

**Comment by joepuzzo** [comment]
Add a nested form dynamically and the nested form can have multiple fields

**Comment by joepuzzo** [comment]
Are you all set with this? Have u tried nested forms?

**Comment by joepuzzo** [comment]
Closing this as its been a while without any updates
