### ISSUE TITLE
InitialValues after call Api

### ISSUE THREAD

**Issue by DMP2-Tech** [react-tools/react-form#193]
Hi,
I want to update the initial values after calling my API.
My API is called with redux and the data is put in a reducers which is accessible via a props.

`let values = this.props.data_forms.data_form[0]`

To update I tried with `defaultValues` with the update of the `props` but it does not work.

I saw  to use `setAllValues` but i can't call `getApi` when the API is finished. 

Can you help me please

Thank's

**Comment by aivils** [comment]
In my case I later use stored formApi

```
<Form>
  { (formApi) => (
    // store here or call function which stores api
    this.formApi = formApi
  ) }
</Form>
```

Server respond code
```
this.formApi.setAllValues(response.data)
```

**Comment by DMP2-Tech** [comment]
Thank's but i have a warning message.

`3webpack-internal:///145:33 Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to componentWillMount.`

**Comment by joepuzzo** [comment]
Yeah you actually want to use the `getApi` prop on form. This is similar to how you use `ref` to get a reference to a component. Let me know if this helps.

**Comment by joepuzzo** [comment]
```
<Form getApi={( api )=>{ this.setApi( api ) } }/>
```

**Comment by joepuzzo** [comment]
Any updates on this or can i close. I think what you want is what is described above

**Comment by DMP2-Tech** [comment]
Thank's.
