### ISSUE TITLE
Form field render prop

### ISSUE THREAD

**Issue by dattusdwaltz** [react-tools/react-form#196]
I've been trying to get my app updated to the latest version of React Form (I'm on 1.3.0 at the moment), but it would appear that using a render prop for custom form fields has regressed since the previous version, making updating the package require rewriting my custom inputs. Are there plans to support render props and functions as children again?

**Comment by joepuzzo** [comment]
Are you referring to creating custom inputs using `FormField(YourComp)` instead of passing in a child func? If not could you elaborate with maybe a small example. I don't remember the old lib supporting a render prop.

**Comment by joepuzzo** [comment]
Yeah just update to the new syntax. It was a design decision when moving to V2. But it really should be a simple change.

**Comment by joepuzzo** [comment]
See the custom input docs.

**Comment by dattusdwaltz** [comment]
Copy, thanks.
