### ISSUE TITLE
TypeError: (0 , N.default) is not a function

### ISSUE THREAD

**Issue by zalishchuk** [react-tools/react-form#198]
My code:
```jsx
<Form onSubmit={console.log}>
  {({ submitForm }) => (
    <form onSubmit={submitForm}>
      <Text field="test" />
      <button type="submit">submit</button>
    </form>
  )}
</Form>
```

The error that I'm getting:
```
Uncaught TypeError: (0 , N.default) is not a function
    at t.value (index.js?0945:1)
    at callComponentWillReceiveProps (react-dom.development.js?cada:6389)
    at updateClassInstance (react-dom.development.js?cada:6575)
    at updateClassComponent (react-dom.development.js?cada:7848)
    at beginWork (react-dom.development.js?cada:8225)
    at performUnitOfWork (react-dom.development.js?cada:10224)
    at workLoop (react-dom.development.js?cada:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
```

```
The above error occurred in the <t> component:
    in t (created by Connect(t))
    in Connect(t) (created by t)
    in t (created by NewTasksPage)
    in div (created by NewTasksPage__Wrapper)
    in NewTasksPage__Wrapper (created by NewTasksPage)
    in NewTasksPage (created by Route)
    in Route (created by BetterRoute)
    in BetterRoute (created by App)
    in Switch (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by withCookies(Connect(App)))
    in withCookies(Connect(App)) (created by Route)
    in Route (created by withRouter(withCookies(Connect(App))))
    in withRouter(withCookies(Connect(App)))
    in I18nextProvider
    in Provider
    in Router (created by BrowserRouter)
    in BrowserRouter
    in CookiesProvider
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

When I add `dontValidateOnMount` prop to `Form` component, it doesn't throw any errors on mount, but if i try to input some text it falls with:

```
Uncaught TypeError: (0 , c.default) is not a function
    at S (index.js?0945:1)
    at eval (index.js?0945:1)
    at dispatch (createStore.js?6413:165)
    at Object.eval [as dispatch] (index.js?e2e7:14)
    at Object.r.setValue (index.js?0945:1)
    at setValue (index.js?0945:1)
    at onChange (index.js?0945:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at Object.invokeGuardedCallback (react-dom.development.js?cada:438)
```

**Versions:**
- react-form - `2.13.0`
- react - `16.2.0`
- react-dom - `16.2.0`

**Comment by zalishchuk** [comment]
Why `react-form` is bundling in so weird way, all dependencies are excluded from `dist/index.js` including `babel-runtime` (required by `babel-plugin-transform-runtime`). So output dist file is not fully prepared for using and does not have development version.

**Comment by zalishchuk** [comment]
So the problem is packages like `babel-runtime` or any used from `node_modules` folder are not being bundled into `dist/index.js` file, because of using `webpack-node-externals` [here](https://github.com/react-tools/react-form/blob/master/config/webpack/webpack.dist.config.js#L9). I don't think it's a good practice, so we should bundle all production dependencies into `dist/index.js` file.

My personal opinion is that using such tools like `redux` here is overhead and `react-form` can have a much smaller size, because now it's 30kb gzipped (about like react itself). Please accept my PR and make a discussion about the possibility of moving to use react built-in approaches.

**Comment by joepuzzo** [comment]
Hmm you seem to be the only person with this issue. This makes me think you may have somthing configured strangley. I ignore node modules because you typically dont bundle node modules with your index as its the job of the dependency management system to ensure they are there.

**Comment by zalishchuk** [comment]
Let me check my configuration files.

**Comment by zalishchuk** [comment]
Seems like `babel-runtime/core-js/json/stringify.js` was required and processed by `file-loader` because of the typo in `module.rules` section of my webpack configuration. Missing parentheses made `stringify.js` parsed by `file-loader` because of `gif` part in my regular expression.

```js
{
  test: /\.png|jpe?g|gif|svg$/,
  use: [
    'file-loader?name=[hash:16].[ext]&outputPath=static/img/',
  ],
}
```

Valid regular expression:
```js
/\.(png|jpe?g|gif|svg)$/
```

**Comment by zalishchuk** [comment]
Seems like `babel-runtime/core-js/json/stringify.js` was required and processed by `file-loader` because of the typo in `module.rules` section of my webpack configuration. Missing parentheses made `stringify.js` parsed by `file-loader` because of `gif` part in my regular expression.

```js
{
  test: /\.png|jpe?g|gif|svg$/,
  use: [
    'file-loader?name=[hash:16].[ext]&outputPath=static/img/',
  ],
}
```

Valid regular expression:
```js
/\.(png|jpe?g|gif|svg)$/
```
