### ISSUE TITLE
Perform non-async validation on touched

### ISSUE THREAD

**Issue by tiffwu** [react-tools/react-form#199]
I see that currently setTouched triggers only async validation. Is there any way to also have setTouched trigger non-async validation?

**Comment by tiffwu** [comment]
Actually, I'm going to just pop my synchronous validators into asyncValidators

**Comment by tiffwu** [comment]
Alright, this is still an issue. I can't use async validators to validate my form state based on multiple fields (e.g. require billing address only if "Separate shipping and billing address" is checked). Is there any other way to trigger validations after each field is setTouched?

**Comment by joepuzzo** [comment]
Ahh im pretty sure it validates on set tocued

**Comment by joepuzzo** [comment]
Hmm i just tool a look. It does when you set value i.e touch a field.. maybe i will update but i have to think if this is a breaking change

**Comment by tiffwu** [comment]
No worries, I'll survive without it.

**Comment by joepuzzo** [comment]
I think im going to add this as i don't think it will be a breaking change. it will simply call sync validation one extra time.

**Comment by joepuzzo** [comment]
This is fixed.
