### ISSUE TITLE
Form Validation on Key Press

### ISSUE THREAD

**Issue by awrenn49** [react-tools/react-form#210]
Is it supposed to be calling the ValidateError function every time a key is pressed? I am using your exact code from the demo. If so, how do I prevent this happening until submit? Thanks!

`    return(
      <Form
        validateSuccess={successValidator}
        validateError={errorValidator} 
        dontValidateOnMount={true}

      >
        { formApi => (
          <form onSubmit={formApi.submitForm} id="form1" className="mb-4">
            <label htmlFor="hello">Hello World</label>
            <Text field="hello" id="hello" />
            <div>{this.state.error}</div>
            <button type="submit" className="btn btn-primary">Submit</button>
          </form>
        )}
      </Form>
    )`

**Comment by joepuzzo** [comment]
It does. I remember having an issue in the past with not validating but i think since i have refactored to use redux i may be able to add a flag to enable this.

**Comment by joepuzzo** [comment]
Just added a prop for this.. see the docs and pull the latest version :) its `validateOnSubmit`

**Comment by mulmulovich** [comment]
is it possible to add this to the type def?
