### ISSUE TITLE
Include non-minified source in npm package

### ISSUE THREAD

**Issue by tiffwu** [react-tools/react-form#213]
Not sure exactly what needs to be done here, but I'd love to see something more useful than this:
<img width="1521" alt="screen shot 2017-12-20 at 5 49 55 pm" src="https://user-images.githubusercontent.com/11621425/34236854-5455a1dc-e5ae-11e7-92b7-643e73271eb4.png">

**Comment by joepuzzo** [comment]
Why not read the source on github ??

**Comment by tiffwu** [comment]
I do. But the source doesn't help me when I'm trying to figure out which component threw an error and all I see is 't' and 'r' in the debugger.

**Comment by joepuzzo** [comment]
Yeah this is just an unfortunate side affect of minification. I wont be including the non minified version because it makes the package bigger. If your really need to play with the source code clone the repo and npm link.

**Comment by joepuzzo** [comment]
Closing this as its not an issue with the lib.
