### ISSUE TITLE
preSubmit on nested forms

### ISSUE THREAD

**Issue by charlieclark** [react-tools/react-form#214]
Awesome work on this lib! So far it's been very ease to use and effective.

I tried adding using preSubmit on a NestedForm and it didn't work. This would be a great feature to have as it would allow further modularization of forms.

**Comment by joepuzzo** [comment]
hmm i will take a look when i get chance.. may have forgotten to add somthing.

**Comment by charlieclark** [comment]
@joepuzzo Any ETA on when you'll be able to take a look at this? This is a pretty major blocker for me in terms of using this lib, and if you think you wont have time to look into it any time soon I may need to look elsewhere. 

Thanks!

**Comment by joepuzzo** [comment]
Sorry i have been swamped lately.. i will take a look tomorrow.

**Comment by charlieclark** [comment]
Any luck? Interestingly I noticed that the preValidate hook does work for the NestedForm, although preSubmit doesn't.

**Comment by joepuzzo** [comment]
Hey @charlieclark Again very sorry I have still not got to it but I think I know whats going on. I call preValidate in the nested forms when it submits but simply need to also call preSubmit.

**Comment by joepuzzo** [comment]
I just looked into this and this was on purpose. You should only use preSubmit on the parent most form because the purpose of presubmit is to modify the values before submission of the whole form. At this point the nested forms have already done their part and sent there values up to the parent. unfortunately this would be complex to solve because of the way things were written. I may keep this in a backlog to look into again if we write a V3 of the lib

**Comment by charlieclark** [comment]
@joepuzzo interesting, I guess that makes sense. Is there any chance you could add in some kind of mapping function that would allow mutating data before it gets passed up to the parent form? Right now what I'm thinking of doing is using the `preValidate` hook to perform my transformations, and store the transformed data in a special `final` field and send that data to the server...

**Comment by joepuzzo** [comment]
Nested forms are drastically simplied/removed in V3! Now use `NestedField` component && field level validation and this will no longer be an issue.
