### ISSUE TITLE
Prepopulate form fields

### ISSUE THREAD

**Issue by kpelelis** [react-tools/react-form#217]
Hey all,

I have been trying to use your framework and I wanted to pre populate some fields with arbitary values (e.g. partially update user information in a form). I was going throught both your documentation and the code and I couldn't find a trivial way to do this. Ideally the form could accept a state object that could be passed on either from its parent or from a redux store.

```
<Form 
  onSubmit={(values) => console.log(values)}
  initialState={this.state}
>
  { formApi => (
    <form onSubmit={formApi.submitForm} id="form-id">
      <label htmlFor="username">Username</label>
      <Text field="name" id="name"/>
      <label htmlFor="firstName">First Name</label>
      <Text field="firstName" id="firstName" />
      <label htmlFor="lastName">Last Name</label>
      <Text field="lastName" id="lastName" />
      <button type="submit" className="mb-4 btn btn-primary">Submit</button>
    </form>
  )}
</Form>
```
Where `state` could be:

```
{
  username: "jdoe",
  firstName: "John",
  lastName: "Doe"
}
```

**Comment by joepuzzo** [comment]
Its in the docs. `setFormState` is what you are looking for

**Comment by KostasPelelis** [comment]
@joepuzzo the API for this method is not really great. This overrides the whole form state instead of just the initial values

**Comment by joepuzzo** [comment]
Are you looking for default values? Because there is a prop for that as well.

**Comment by joepuzzo** [comment]
@KostasPelelis updates or can i close?

**Comment by prenaut41** [comment]
It would be really (really) nice if there was a property for values that could be passed into the render for each field.  This would be for situations where there is already an entity existing in the database and we are retrieving it so the user can modify it.  This should be separate from defaultValue, which is what should be applied when a field actually defaults to some value in the absence of a user-entered value.  
<Text field="MyFieldName" value="Existing Value"></Text>

**Comment by joepuzzo** [comment]
`defaultValues` will achieve this. V3 is out so i would go check that out and see if it works better.
