### ISSUE TITLE
Redux as a dependency?

### ISSUE THREAD

**Issue by anselmdk** [react-tools/react-form#220]
As [Apollo is moving away from Redux](https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2), I'm looking into a React form library that doesn't use Redux. I'm considering this one. There's no mention of Redux, but I can see in `package.json` that Redux is added as a dependency.

Will this library work without Redux?

**Comment by joepuzzo** [comment]
Redux is used under the hood but it’s completely abstracted away from the end user
