### ISSUE TITLE
Add callback for when values have changed rather than formState

### ISSUE THREAD

**Issue by z-vr** [react-tools/react-form#225]
It would be useful to be able to react to events when only value of the fields has changed, and not the whole form, please.

**Comment by joepuzzo** [comment]
you can tie into the onChange event just like in any old input.

**Comment by joepuzzo** [comment]
Can I close this ?

**Comment by z-vr** [comment]
@joepuzzo yep thanks I've figured it out that I have to manually pass `onChange` handler, although this is more work than if we could have an event by the Form -- it's possible.
