### ISSUE TITLE
Unnecessary dependancies 

### ISSUE THREAD

**Issue by ro-savage** [react-tools/react-form#227]
I was looking at using react-form because of it being light-weight, however I noticed a few dep that I had questions about

`circular-json` is no longer in the code base.

`redux-logger` should only be a dev dependancy. Currently is commented out, but if you want to use it for dev, normal way is something like

```js 
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./configureStore.prod')
} else {
  module.exports = require('./configureStore.dev')
}
```

And then in your dev store, you use redux logger, and in the prod store you don't.

Happy to do a PR if you like.

**Comment by joepuzzo** [comment]
You're right.. i can remove in next release.. will probs leave logger as dev dep :)

**Comment by zalishchuk** [comment]
@ro-savage if you are looking for a lightweight, fast and flexible react form management, you should try [react-final-form](https://github.com/final-form/react-final-form).

**Comment by joepuzzo** [comment]
V3 is out. Check out the updates and removed dependencies.
