### ISSUE TITLE
FormField and props, why use getters?

### ISSUE THREAD

**Issue by ro-savage** [react-tools/react-form#230]
When using the FormField component, we receive a bunch of props that are getters/functions.

`getValue()`, `getTouched()`, `getFieldName()` etc.
https://github.com/react-tools/react-form/blob/9934a62a0cbb355418919bca684fe4b057f11ac0/src/components/FormField.js#L93-L98

Looking are the source, I couldn't see why these couldn't just be the values.

That way in our component we can do `props.value`, `props.fieldName`. More inline which expected behaviour in React.

Am I missing something?

```js
class TextWrapper extends Component {
  render() {
    return (
      <input
        {...this.props}
        value={props.value || ''} // instead of fieldApi.getValue()
        onChange={(e) => {
          setValue(e.target.value);
          if (onChange) {
            onChange(e.target.value, e);
          }
        }}
      />
    );
  }
}

const Text = FormField(TextWrapper);
```

**Comment by joepuzzo** [comment]
If I remember correctly the getters have to be passes because the values will be out of date otherwise but i have to go back and look. Not the best answer rn but im like 90% sure there was an issue with doing this.

**Comment by ro-savage** [comment]
@joepuzzo 

If the issue is `FormField.js` being out of date because it doesn't re-render on a field change.

Then `FormField.` could become a connected component and receive required fields values straight from redux, rather than relaying on `context` and the connected `Form`.

It might also make the `shouldComponentUpdate` simpler and more accurate.

As far as I can see  the current `fieldApi.getValue()` works fine, its just unusual paradigm for a react/redux component.

When you are working on v3, feel free to reach out, and I'd like to contribute since we just moved our massive forms from an internally built form component to react-form and react-form seems really great and well built!

**Comment by tannerlinsley** [comment]
Ro, if you’d like to get a peek at some of the new features and changes,
head over to the FAAC branch and look at the changelog. Let me know what
you think!

**Comment by ro-savage** [comment]
Change log looks good. I haven't really done much with FAAC, so not on top of the benefits.

Here's some suggestions from out couple days converting over
- [ ] Field level validation
- [ ] Input static values are props rather than getters (getValue(), getFieldName(), etc)
- [ ] Automatically handling of dynamic nested forms deleting fields (Right now we do `this.props.removeValue('tickets', this.props.index)` which worked well but originally expected we'd be able do it off the formApi of the nested form `formApi.remove('tickets', this.props.index)`)
- [ ] A way to somehow have a single input create/manipulate multiple fields (e.g. we have a single input for location search and we get an objected returned that we save as multiple fields in our form/redux/db. Right now we use onSubmit to format it, alternative we could have made hidden inputs and used formApi to add the data to each of the fields)
- [ ] `dontValidateOnMount` feels like it should be `validateOnMount` and the default being it does not validate on mount
- [ ] Better docs on validation. Seperate pages for the APIs
- [ ] Update docs do not use `i` as a key which causes react rendering issues (see #221)
- [ ] Performance improvements (in follow up post)

One of the things we had in our library, which worked well for us but may not be suitable for everyone is that we debounced our inputs before passing up their values to react/redux.

This mean only the input was re-rendering each time, no validation, etc was going on until a user had stopped typing for more than 200ms. We found this was enough that if a user tabbed and started typing it has no affect, but as long as they were typing we weren't re-rendering anything outside that one input/field.

As I said, overall it works really well. In the past we'd used redux-form and found it way too slow. So I was a bit worried when I saw this was using redux as well but it seems to still be reasonably performant (admittedly I have used redux-form for about a year).

**Comment by ro-savage** [comment]
In terms of performance. here is an example between our internal form tool (state managed in React) and react-form.

This is a complex form, its a form, with dynamic subform, that has another dynamic subform. Total inputs on screen is 40, of which 3 have validation. My chrome browser is running 6x slower (in chrome dev tools)

There is 0 lag filling in ours (only lag is actually the gif no the form)
While using react-form, the form is unusable.

![g4cwsrsyqt](https://user-images.githubusercontent.com/9244507/35088515-2d9c1512-fc88-11e7-9547-235a8098af78.gif)

**Comment by tannerlinsley** [comment]
The `FormApi` and `withFormApi` component/HOC will likely help you with complex fields managing more than just their field. It gives you access to the nearest parent form's base api, allowing you all the creative freedom you may need. Is that more in line with what you're thinking?

**Comment by tannerlinsley** [comment]
Also, let's try and move these ideas into the new "projects" section for the repo
