### ISSUE TITLE
Validation of every field runs on every press

### ISSUE THREAD

**Issue by ro-savage** [react-tools/react-form#231]
One of the things that may cause slowdowns is that validation runs on every keypress for every field.

As a prototype I made a custom input that receives a validation function, runs it internally on `componentWillReceiveProps` and then uses `setError` to set an error just for that input.

This means validation runs only on the component that is being changed. It should still be very possible to run validation on everything when submitting and when mounting.

The user would still pass a single `validateError` prop to `Form` and internally `FormField` would then pass down the validators to the input to validate (or `FormField` it could do the validation).

Is this something you are interested in exploring and willing to accept a PR for?

**Comment by joepuzzo** [comment]
So i have explored field level validation in the past and it gets messy and also you loose some capabilities. For example in many use cases updating a field, FOR EXAMPLE: a gender field, could result in another field becoming invalid. In these use cases it becomes helpful for everything to validate. Also, there are many lifecycle hooks that occur when you type in a field rn so its not as simple as you may think to add this feature. That being said, you are still welcome to explore the idea. Just know that i have and while i cant think of all the issues I ran into off the top of my head, there are def a few challenges with this one. Eventually we may put out a V3 that simpifies the library and possibly allows this but thats a ways away.

**Comment by ro-savage** [comment]
Having an option to run validation on every field, every time, would allow the majority of users to have the performance increase of field-level validation while still allowing edge cases where needed.

Personally, it makes sense if you have one field that relies on validation from another, to use the onChange event to monitor the change.

Happy to close the issue and I'll investigate further in a fork along with other possible performance improvements.
