### ISSUE TITLE
defaultValues use this.state.XXX not Working

### ISSUE THREAD

**Issue by Luis-Chen** [react-tools/react-form#233]
#### `this.state.product` get values from api  and  no problem
````
	componentDidMount() {
		if (this.props.id !== undefined) {
			axios
				.get('http://localhost:8001/product', {
					params: {
						id: this.props.id
					}
				})
				.then(response => {
					this.setState({ product: response.data })
					console.log(this.state.product)
				})
				.catch(error => {
					console.log(error)
				})
		}
	}
````

#### but `name:product.name` isn`t working

````
class ProductForm extends React.Component {
	constructor(props) {
		super(props)
		this.state = {
			product: []
		}
	}

	let { product } = this.state

	<Form defaultValues={{ name: product.name, model: 'adfa', ean: 'asdf' }} >
		{formApi => (
			<form onSubmit={formApi.submitForm}>
				<Text field="name" />
				<Text field="model" />
				<Text field="ean" />
			</form>
		)}
	</Form>

}

````

**Comment by joepuzzo** [comment]
Ahh all default values is doing is setting the initial values on the internal state.. so it should be working. I have a feeling something else is going on here.

**Comment by Luis-Chen** [comment]
Maybe,this problem relation to conponentDidMount()
codesandbox test:
> https://codesandbox.io/s/327r8qqn16

**Comment by Luis-Chen** [comment]
@joepuzzo so `defaultValues` not support React LifeCycle ? if my initial values need to call form api and setState `defaultValues` cant get value that updated?

**Comment by MrWhiteNerdy** [comment]
I'm having this exact same issue.

**Comment by Luis-Chen** [comment]
finally i try  success to use  shouldComponentUpdate(nextProps, nextState) 

in my example

`
class ProductForm extends React.Component {
	constructor(props) {
		super(props)
		this.state = {
			product: []
		}
	}
        componentDidMount(){
          axios.get('http://server.url').then(response=>(this.setState(product)))
        }
        shouldComponentUpdate(nextProps, nextState) {
		console.log(nextState)
		if (nextState.page.length !== 0) {
			return true
		}
	}
	let { product } = this.state

	<Form defaultValues={{ name: product.name, model: 'adfa', ean: 'asdf' }} >
		{formApi => (
			<form onSubmit={formApi.submitForm}>
				<Text field="name" />
				<Text field="model" />
				<Text field="ean" />
			</form>
		)}
	</Form>

}
`

then it will re-render

**Comment by joepuzzo** [comment]
So your fix was to basically rerender the form.. I would NOT recommend this. Instead i would use the getApi to get the `formApi` and then use the set `value` or `setValues`
