### ISSUE TITLE
custom button send the form when onClick() be triggered

### ISSUE THREAD

**Issue by Luis-Chen** [react-tools/react-form#235]
I create a Custom Input  to upload file to firebase,

code 

````
     let { fieldApi } = this.props

     let getImage = e => {
		let file = e.target.files[0]
		let reader = new FileReader()
		console.log(reader.result)
		reader.onloadend = () => {
			console.log(reader.result)
			this.setState({ blob: reader.result })
		}
		reader.readAsDataURL(file)
     }
    let upload = () => {
			let { blob } = this.state
			let path = 'images/category'
			firebaseUpload(blob, path)
     }
    return (
	<div>
	   <input onChange={e => getImage(e)} type="file" />
	   <button onClick={e => upload}>addf</button>
	</div>
 )
````

when I click button to upload file the button also send the form 

Gif Demo

![https://media.giphy.com/media/l4pT0qV2legImpLG0/giphy.gif](https://media.giphy.com/media/l4pT0qV2legImpLG0/giphy.gif)

**Comment by donovanhiland** [comment]
the default type of an html button is `submit` which will submit any form the button is inside. Try setting the `type="button"` on the button

**Comment by joepuzzo** [comment]
Yup be careful with type="button" as it will not submit a form.
