### ISSUE TITLE
NestedForm is not updating it's child on state or context change

### ISSUE THREAD

**Issue by HunorMarton** [react-tools/react-form#236]
In the following structure the second console log is not reached on context nor state update:
```
  render() {

    console.log('This message shows up on state or context update');

    return (
      <NestedForm ...>
        <Form ...>
          { formApi => {

            console.log('This message is NOT reached on state or context update');

            return (
              <MyCustomField 
                stateValue={this.state.value} 
                contextValue={this.context.value} 
                ...
              />
            );
          }}
        </Form>
      </NestedForm>
    );
 } 
```

I found a fix for it by adding extra parameters to the NestedForm component like below but I don't think it's nice this way.
```
  <NestedForm trigger={this.state.value} >
```

The feature I'm trying to achieve this way is async default value for Country field. Is there any better way for that?

**Comment by joepuzzo** [comment]
We are actively working on a V3 of react-form and are considering drastically simplifying NestedForms. The fix you have is what i have actually done in the past to resolve this. So stand by for V3 and keep what you have for now.

**Comment by joepuzzo** [comment]
V3 is out!
