### ISSUE TITLE
What happens to a form value when I no longer render its corresponding form control?

### ISSUE THREAD

**Issue by PolyPik** [react-tools/react-form#238]
I have a situation where I need to dynamically render certain inputs based on the data that is fetched each time a certain `select` component is changed.

Suppose that the change makes a certain field "not applicable" and is thus removed from rendering, is the value also removed or does it still remain?

One work around I've thought of, in case the value is retained, is to call `setValue('fieldName', null)` on the non-applicable field as there is no `formApi` method to delete a non-array value.

**Comment by joepuzzo** [comment]
Working on improving this exact thing in V3 which we are working on now! Basically on componentWillUnmount we will take the field out.

**Comment by joepuzzo** [comment]
Take a look at V3 you can achive this in two ways. either by using the add and remove values from within an array field. or simply add or remove it from DOM and it will take itself out when it unmounts
