### ISSUE TITLE
React Form 3.0

### ISSUE THREAD

**Issue by joepuzzo** [react-tools/react-form#240]
Opening issue for questions and info on V3 of react form. Its being actively developed.

**Comment by warrenmcquinn** [comment]
Looks great, guys! I have some form components that I'm considering porting to `react-form`. Should I be concerned going forward about any major issues porting from V2 to V3.0?

**Comment by EscoCreeks** [comment]
Will there be any formatting function to give to the fields ? In order to have a nicely rendered input without its core value being changed ?

**Comment by joepuzzo** [comment]
Formatting is on the list of things. you have always been able to achieve this with the `preValidate` function but we might add a format prop to the input @tannerlinsley what do you think of this. I know i already played with this idea before and there is already a hidden format action in the redux actions.

**Comment by joepuzzo** [comment]
@warrenmcquinn Yes so there will be breaking changes mostly around nested forms and validation.
You can start to port over but i would give this advice. 1. Try to NOT use nested forms 2. Prepare for the single validator that gets passed to the `Form` to turn into validators on a per field basis.

**Comment by mgutz** [comment]
@joepuzzo A single validator is still allowed right? While per field validations are nice, most complicated validations require dealing with multiple values from the form and props.

**Comment by joepuzzo** [comment]
@tannerlinsley what are you thinking on this? ^^^^

**Comment by joepuzzo** [comment]
@tannerlinsley @mgutz im thinking no we dont allow a single validator, BUT, we expose all the fields errors and values etc to each inputs validation function

**Comment by tannerlinsley** [comment]
There will still be a single validation method available at the form level.
But it will function almost exactly like the validator on nested fields,
allowing you to compare and ensure all of the values at the form level.

**Comment by joepuzzo** [comment]
@mgutz This is being discussed ^^^ lol we will let you know what we come up with.

**Comment by joepuzzo** [comment]
@mgutz Yes we are keeping it so you can do either form or field level

**Comment by joepuzzo** [comment]
React Form 3.0 is now released!! closing
