### ISSUE TITLE
beta on npm empty

### ISSUE THREAD

**Issue by philipheinser** [react-tools/react-form#243]
when I install the latest version from nam i get an empty folder :(

**Comment by tranvansang** [comment]
i confirmed the issue. I got folder of 4 files `CHANGELOG.md, LICENSE, package.json, README.md`.

Tried with both `npm 5.6.0` and `yarn 1.3.2`

**Comment by tranvansang** [comment]
temporary work around `npm install --save react-form@2`

**Comment by joepuzzo** [comment]
@tannerlinsley any ideas what might be happening here

**Comment by tannerlinsley** [comment]
Yeah. I'll issue a fix.

**Comment by joepuzzo** [comment]
This issue should be fixed.
