### ISSUE TITLE
Text field of type number doesn't support a default value of 0

### ISSUE THREAD

**Issue by avrahams1** [react-tools/react-form#247]
The bug is here:
https://github.com/react-tools/react-form/blob/master/src/components/form-fields/Text.js
At line 20.

If you make a Text input of type "number", a default value of 0 isn't shown since the condition there just checks the "truthiness" of the value, rather than the value.

Might be a bug in other inputs where the value can be a number.

I'm using version 2.16.2.

Example code:
```
<Form defaultValues={{ a: 0 }}>
                {formApi => (
                    <form onSubmit={formApi.submitForm}>
                        <Text field="a" type="number"></Text>
                    </form>
                )}
</Form>
```

The text input is empty, although it should have the value 0.
If you change the {a:0} to {a:1} it works perfectly and the input shows the default value of 1.

**Comment by joepuzzo** [comment]
We will get this fixed in V3

**Comment by avrahams1** [comment]
Is it possible for me to submit a pull request for version 2 to fix this minor bug?
It's literally 1 line.

If so, how would I go about doing that?
I tried cloning the repo and pushing a new branch, I don't have permissions to push a new branch.

**Comment by joepuzzo** [comment]
Sure.. right now we have issue where if you install it tho you need to include `@2.x.x` because we mistakenly published a V3 without tag. But other than that go ahead and make pull request

**Comment by joepuzzo** [comment]
We are also getting real close to releaseing V3 tho lol

**Comment by avrahams1** [comment]
Yeah, I ran into that little bug, didn't take me long to figure out I had to download V2.

How close are you to releasing V3?
Will it break the API in a significant way?

About the pull request - can you please explain what exact steps I should do?
I cloned the project and added the code, now what?
I don't have permissions to push to the server, even on a newly created branch, how am I supposed to push my changes to the server to create the pull request?
Sorry if it's a dumb question, I've never done thing before :(

**Comment by joepuzzo** [comment]
Hey yeah no such thing as a dumb question in development lol. Typically you fork the repo and then do a pull request with the fork .. there will be breaking changes and we will put out a changelog for that

**Comment by avrahams1** [comment]
Created a pull request, The tests run successfully, please tell me if I did anything wrong.

Should I have manually changed the version in the package.json?

**Comment by avrahams1** [comment]
Once he merges my pull request both our problems will be solved :)

**Comment by joepuzzo** [comment]
Its all in :) V2.16.3
