### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by pld000** [react-tools/react-form#255]
Hello.
Thank you for your work!! v3 is very cool, and we of course will use it in future, but now we need old documentation v2.11.0, can you help us ?

**Comment by joepuzzo** [comment]
So the documentation is basically the same but with the exception of the changes that can be found in the change-log https://github.com/react-tools/react-form/blob/master/CHANGELOG.md . That being said we could probably look to host old docs somewhere but its was lower priority

**Comment by mjhm** [comment]
@pld000 It looks like you can self host the documentation if you like.

```
git clone https://github.com/react-tools/react-form.git
cd react-form
git co v2.16.3
npm install
npm start
```

Then you should have the docs at `http://localhost:4005`

**Comment by pld000** [comment]
ok, thank you!

**Comment by joepuzzo** [comment]
LOL @mjhm yeah that works. Again maybe we can host them somewhere.

**Comment by sangel10** [comment]
Agree about hosting the old docs somewhere. I'm on version 2.X and trying to use nested fields, but the documentation only shows an example with `<NestedField>` whereas the change log suggests what I should be using is `<NestedForm />`. I tried running the docs locally but they only have documentation for `<NestedField />`

**Comment by joepuzzo** [comment]
Old docs are now live! Go to the bottom of README for link.
