### ISSUE TITLE
redux integration

### ISSUE THREAD

**Issue by pak11273** [react-tools/react-form#261]
I'd like to be able to use react-form but keep my state in the redux store.  @tannerlinsley You stated "I have a simple 20 line adapter that uses the lifecycle hooks to keep the form state in redux for HMR" on this [reddit](https://www.reddit.com/r/reactjs/comments/5h17fy/react_form_a_new_lightweight_utility_for_building/).  Could you post that code or give a sample implementation?

**Comment by joepuzzo** [comment]
So under the covers the state is actually already in a redux store. But, if you want to keep it external simply use the on change function that you can pass to the Form component and u can trigger actions based on that. Or maybe what tanner was referring to in that post was tieing into the life cycle events such as onSubmit to, for example, trigger a form submit action in your store

**Comment by pak11273** [comment]
Ok I've looked into some of the code and I see that a whole new store is being created.  This feels like an antipattern.  I really don't want 2 redux stores in my app.  I also would like the benefit of seeing my form state in redux dev tools for debugging.  I think the life cycle events were referring to react life cycle methods.  If this is already redux under the hood, then isn't onSubmit performing a redux action anways?

**Comment by tannerlinsley** [comment]
The two stores need to be separate. They have different concerns entirely.
But we could bring back the loadState and saveState props methods to make
this possible. Basically, on saveState, you store the state wherever you
want, usually in your redux store under a formID. Then you use loadState to
rehydrate the form state on mount (if it exists). This makes the state
accessible to your app store without making any large assumptions to either
your own code or react forms. Thoughts?

**Comment by pak11273** [comment]
I'm not picturing what the loadprops is for, but maybe I'm thinking about it wrong.  The use case I need is after submitting a form I am redirected to another page and from that page I need access to some of the previous form values.  If I can access those values with mapStateToProps I'm good as gold.

**Comment by joepuzzo** [comment]
If thats the case why dont you just save the values from the first form submission via onSubmit?

**Comment by tannerlinsley** [comment]
Agreed. You don't need anything special to do that. Just place the form
values into your redux state on successful submit and access them later.

**Comment by pak11273** [comment]
Yes this was my original plan with my own react form.  But that is why I searched for a plugin where I wouldn't have to do that.  You don't have to do that with redux-form, but it is a little too over engineered for what I need.  Isn't this what your saveState method does?  I'd like to not have to create an action/reducer for something so trivial.

**Comment by tannerlinsley** [comment]
This isn’t something we’re going to be able to include with react-form, but
you could easily build an HOC that does this for you.
