### ISSUE TITLE
`removeValue` function in `fieldApi` actually adds a value.

### ISSUE THREAD

**Issue by cheong38** [react-tools/react-form#265]
In `Field.js` file, around 90 ~ 92 lines

``` 
...
 addValue: value => formApi.addValue(fullField, value),
 removeValue: index => formApi.addValue(fullField, index),
...
```

value of `removeValue` is calling `formApi.addValue`.
But I think it should call `formApi.removeValue`.

**Comment by joepuzzo** [comment]
Are u sure? The demo on the docs works and it uses this? Also i just checked code and it looks like it callles remove. What version pf lib are u using

**Comment by cheong38** [comment]
Please check that in [this link](https://github.com/react-tools/react-form/blob/master/src/components/Field.js).
At line 92, you will find
```
removeValue: index => formApi.addValue(fullField, index)
```

**Comment by joepuzzo** [comment]
Oh snap lol will fix right away I had looked in Form and not Field

**Comment by joepuzzo** [comment]
Fixed in V3.2.3

**Comment by cheong38** [comment]
Thanks! 👍

**Comment by FredyC** [comment]
@joepuzzo I am confused right now. Version 3.5.5 and `addValue` is still there :) Looks like it happened in PR #278 , but I am not sure why. Perhaps I am misunderstanding something here?

https://github.com/react-tools/react-form/blob/c2337923284425e10620add45647e332be9c0459/src/components/Field.js#L93
