### ISSUE TITLE
Pass Through Props to Form Component

### ISSUE THREAD

**Issue by DavidHooper** [react-tools/react-form#267]
I think non component specific props should be passed through to the component defined on Form.
For the example below, component and onSubmit shouldn't be passed through because it has to do with the Form props. However className should be passed through like a normal prop.

```
 <Form 
    component={SomeFormComponent}
    onSubmit={handleSubmit}
    className="row col-6"
 />

const SomFormComponent = ({ formApi, className }) => (
  // only formApi is passed through
  // expected className to equal 'row col-6'
);
```

**Comment by joepuzzo** [comment]
This is unnecessary for forms. Unlike the other elements in react form. With form you define the native form element so u can just pass class name to it

**Comment by joepuzzo** [comment]
Does this make sense? Can i close?

**Comment by joepuzzo** [comment]
Closing this unless it needs further review

**Comment by DavidHooper** [comment]
It doesn't make sense to not pass through the props because you may want a form to be controlled from a parent component.

I have another case where there is a submit button and a cancel button on the form. How is the cancel button supposed to communicate with the parent component to close the form or do whatever?

**Comment by DavidHooper** [comment]
Happy to create a PR for this if you're happy with the proposed change.

**Comment by DavidHooper** [comment]
The proposed change was for having the parent component be able to pass other props such as functions. However, on further you've provided a render function which can achieve the same result.
