### ISSUE TITLE
React-form version is not specified in documentation https://react-form.js.org/

### ISSUE THREAD

**Issue by AlexBazer** [react-tools/react-form#270]
Hi. Thanks for your hard work guys.

Tried to find out why validation hook does not work running 2.x version

It'll be really nice to have documentation for each different version, what do you think?

**Comment by joepuzzo** [comment]
This is kind of a dup of this https://github.com/react-tools/react-form/issues/255 issue so im going to close and we can chat over there but yeah we may deploy the old docs somewhere when we get a chance.
