### ISSUE TITLE
Docs reflect deprecated elements For eg: Radio Group

### ISSUE THREAD

**Issue by BlackBeast** [react-tools/react-form#272]
Its great that you guys are going with the pace. But i think its better to keep the docs updated as well,
Because when the user search for stuffs for implementation, it gives a false impression of the library.
Hope you guys update it soon. Thanks in advance.

**Comment by joepuzzo** [comment]
Nope docs are correct changelog is incorrect closing

**Comment by joepuzzo** [comment]
I will update changelod
