### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by sangel10** [react-tools/react-form#273]
Is there a suggested way to have conditional fields?

For example say I have 2 form fields that are related, a user can be of type A or type B. Type A can then either have title W or X and type B can have title X, Y, or Z. 

What would be the best way to accomplish this?

**Comment by joepuzzo** [comment]
I would just use react and conditionally render fields. When they are taken out reacts lifecycle events will get called and the lib removes them from form :)

**Comment by joepuzzo** [comment]
closing
