### ISSUE TITLE
Multiple for Select

### ISSUE THREAD

**Issue by passionInfinite** [react-tools/react-form#275]
I would like to contribute in the feature to have Select component behave as multi select if multiple is true.
we need to change the value according to the multi select also we need to concat the selected value in onChange function. Any thought?

**Comment by joepuzzo** [comment]
It sounds like you have idea of how you would build this.. do you have snippet of code?

**Comment by passionInfinite** [comment]
Can I send PR? @joepuzzo

**Comment by passionInfinite** [comment]
I am working on It but I will definitely need your help buddy! @joepuzzo

**Comment by passionInfinite** [comment]
@joepuzzo check PR #277 and help me by adding some test cases.

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?selectedKind=Inputs&selectedStory=Multi%20Select%20Input&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel Check out informed. I added a multiselect!!!
