### ISSUE TITLE
Incorrect errors in Form Api

### ISSUE THREAD

**Issue by artemirq** [react-tools/react-form#279]
Hi! I have following code:

```
const haveError = (errors: Object, field: string) => (
    errors && errors.hasOwnProperty(field)
);

const readError = (errors: Object, field: string) => (
    haveError(errors, field) ? errors[field] : null
);

const RegisterForm = () => (
    <Form validate={validateMethod} render={({ errors }) => (
            <form>

                // this showing not empty object while really validateMethod return empty object
                { console.log(errors) } 

                { haveError(errors, 'email') && <small>{readError(errors, 'email')}</small> }
                <Text field='email' type='email'/>

                { haveError(errors, 'password') && <small>{readError(errors, 'password')}</small> }
                <Text field='password' type='password'/>

                { haveError(errors, 'repeatPassword') && <small>{readError(errors, 'repeatPassword')}</small> }
                <Text field='repeatPassword' type='password'/>
            </form>
    )}/>
);
```

On change values in form, validateMethod on line 43 showing empty object. I mean -  **errors in form api should be empty**, but **not empty**

![image](https://user-images.githubusercontent.com/17342159/37418219-ca336942-27c2-11e8-9af2-ef34d3920080.png)

**Comment by joepuzzo** [comment]
Im sorry im not following? Can you put your validator and also describe the speps you take to get those logs?

**Comment by artemirq** [comment]
@joepuzzo Im already migrated to redux-form and this code with small changes work there. I do not know why you need more information, I've described enough

**Comment by joepuzzo** [comment]
You said there was an issue with incorrect errors but did not even put your validator?

**Comment by joepuzzo** [comment]
`<Form validate={validateMethod} render={({ errors }) => (` it would be helpful to see your `validateMethod`

**Comment by artemirq** [comment]
@joepuzzo See console.log in screenshot. At `index.js:43` is Object, returned by validateMethod. Why you need the source of validator, if i told you, what value validator return?

**Comment by joepuzzo** [comment]
You are suggesting that react form is not setting the correct errors... the console.log shows the result of a function, the `validateMethod`. Having the log is does not help because that show what react form set on the errors object.. how did react for set the errors? Well it used your `validateMethod`. Therefore the issue probably exists in that function.

**Comment by artemirq** [comment]
![image](https://user-images.githubusercontent.com/17342159/37790875-c28b33b2-2e18-11e8-93b4-c807cb159569.png)
Rly? It normally work with `redux-form`. Anyway `redux-form` better, i don't see why you're trying maintenance this bike

**Comment by joepuzzo** [comment]
Try using redux form in IE with more than 30 inputs ;) but if redux form works better for you then it works better for you :) this works better for me
