### ISSUE TITLE
Promise support for onSubmit

### ISSUE THREAD

**Issue by marshallswain** [react-tools/react-form#28]
I've put some more thought into async support and have identified another area where it would be very useful.  It would be nice to have Promise support built into form.js, here: https://github.com/tannerlinsley/react-form/blob/master/src/form.js#L137

So, `onSubmit` could accept a function that returns a promise.  We could create two lifecycle methods for handling the promise.
 - `onSubmitSuccess` would run if the promise resolves.
 - `onSubmitError` would run if the promise is rejected.

Adding promise support to `onSubmit` would also make it possible to support standardized error messages from the server.  So the server could send back an error object with a `message` property that could show up in the UI, automatically.

**Comment by tannerlinsley** [comment]
This is super interesting.  I'll start looking into the possibilities in the code and keep you up to date here.

**Comment by vutran47** [comment]
At this state, `postSubmit` is also pretty useless since it will be called anyway without the results. My current workaround is to call `resetForm` manually since it's the 4th argument passed to `submit`. This is very much an implementation detail and should not be used this way.

```js
submit = (v, s, p, f) => submit(v).then(f.resetForm)
```

**Comment by chuan137** [comment]
I smell feathers here :)

**Comment by tannerlinsley** [comment]
Feathers?  Wha do you mean?

**Comment by chuan137** [comment]
It is a light joke, I deleted it, because feathersjs is not so popular that everyone will get it :) But this is the background

This proposal will make `preSubmit`, `onSubmit` and `postSubmit` functions like the hooks in feathersjs, each of them will return a promise and they would await the async action of the previous hook. 

And I think @marshallswain  is one of the authors of feathersjs.

**Comment by marshallswain** [comment]
Yep.  @chuan137's got me.  Inspired by [Feathers](http://feathersjs.com/).

**Comment by thomas-p-wilson** [comment]
As a feathers user, I am most definitely in favour!

**Comment by joepuzzo** [comment]
Working on getting V2 rolled out soon. This supports Asynchronous validation. Stay tuned!

**Comment by joepuzzo** [comment]
Async validation now supported!

**Comment by seniorquico** [comment]
It appears [async submit](https://github.com/react-tools/react-form/pull/226) is now supported, too! (Similar to the proposal found in this issue.)
