### ISSUE TITLE
setAllTouched updates the Form component too many times

### ISSUE THREAD

**Issue by enisdenjo** [react-tools/react-form#285]
I have a quite large Form, around 20-25 `<input />` components inside it. When I submit the Form, it is **updated 20-25 times** just because of **setAllTouched**!

It is very inconvinient as the UI hangs/blocks until the updates are done...

The problem is that `setAllTouched` recursively dispatches the `setTouched` action for EVERY INDIVIDUAL input node. Resulting in: **NUM_OF_INPUTS = NUM_OF_UPDATES** on submit.

Is there a parameter with which I can disable this function?

**Comment by joepuzzo** [comment]
So are you seeing performance issues? There is an optimization that only renders the inputs themselves when something relevant to them changes but the form is supposed to rerender in this case because it truly has changed.

**Comment by joepuzzo** [comment]
In other words yes because of the recursive nature of the lib yes EVERY INDIVIDUAL input will receive an action. This is actually very important because it makes sure all of react forms lifecycle events occur, such as validation.

**Comment by enisdenjo** [comment]
Hey @joepuzzo,

I know that every individual node should receive the new state, but calling `dispatch` in a loop for each node means that instead of updating the Form **ONCE** with `touched: { ...all: true }`; the Form is updated **N** times with `touched: { node1: true }`, then `touched: { node1: true, node2: true }` etc.

And regarding your first question, yes I am seeing huge perfomance impact as the Form lags for ~1-2sec onSubmit. 

I hope you understand my point.

**Comment by enisdenjo** [comment]
Inside the `react-form/src/components/Form.js` the following modification should be done:

Instad of:
```javascript
setAllTouched = () => {
  this.recurseUpAllNodes(node => {
    if (node.nested) {
      return
    }
    if (node.fullField) {
      this.props.dispatch(actions.setTouched({ field: node.fullField, value: true }))
    }
  })
}
```

It should be something like this:
```javascript
setAllTouched = () => {
  const nodeFields = [];

  this.recureseUpAllNodes((node) => {
    if (node.nested) {
      return;
    }
    if (node.fullField) {
      nodeFields.push(node.fullField);
    }
  });

  if (nodeFields.length > 0) {
    this.props.dispatch(actions.setAllTouched({ fields: nodeFields, value: true }));
  }
}
```

Where the `actions.setAllTouched` will set the `touched: true` on the array of fields with **1** reducer call. Meaning the the Form will update with `touched: { ...all: true }` right away, instead of the above mentioned way.

**Comment by joepuzzo** [comment]
Hmmm I think im liking this idea lol

**Comment by joepuzzo** [comment]
let me give it a shot stand by

**Comment by joepuzzo** [comment]
Ok this is updated in the latest patch release!

**Comment by joepuzzo** [comment]
```
  setAllTouched = async () => {
    let touched = {}
    await this.recurseUpAllNodes(node => {
      if (node.nested) {
        return
      }
      if (node.fullField) {
        touched = Utils.set(touched, node.fullField, true)
      }
    })
    this.props.dispatch(actions.setAllTouched(touched))
  }
```

Thats what i ended up doing ^^^^

**Comment by enisdenjo** [comment]
Super sweet! Thanks and I will test it tomorrow. 😁

**Comment by enisdenjo** [comment]
Hey @joepuzzo, upon upgrading the patch version from v3.4.**2** to v3.4.**3** this issue is back again...

**Comment by enisdenjo** [comment]
the Form component has the following logic again:

```js
this.setAllTouched = function () {
  // Set touched is unique because we dont want to set touched on nested fields
  // We also dont want to call the internal setTouched because that would
  // Execute validation.
  this.recurseUpAllNodes(function (node) {
    if (node.nested) {
      return;
    }
    if (node.fullField) {
      this.props.dispatch(actions.setTouched({ field: node.fullField, value: true }));
    }
  });
};
```

**Comment by joepuzzo** [comment]
Stand by

**Comment by joepuzzo** [comment]
My bad.. was a git mistake i had made .. this is now fixed

**Comment by enisdenjo** [comment]
Thanks!
