### ISSUE TITLE
Password confirmation validation

### ISSUE THREAD

**Issue by ralphholzmann** [react-tools/react-form#286]
In working on a sign up page for my app, I wanted to add a validation step to ensure that the `password` field and the `confirm` field contained the same value before submitting the form. I was able to accomplish this like so (reduced to a base case):

```jsx
validatePassword(value = '') {
  if (value.length < 8) {
    return {
      error: 'Password must be at least 8 characters'
    }
  }
}

validateConfirmPassword(value = '') {
  const password = this.formApi.getFormState().values.password;
  if (password !== value) {
    return { error: 'Passwords do not match' };
  }
}

render() {
  return (
    <Form getApi={(api) => { this.formApi = api; }}>
      <Text field="password" type="password" validate={this.validatePassword} />
      <Text field="confirm" type="password" validate={this.validateConfirmPassword} />
    </Form>
  )
}
```

This works just fine, but is this a recommended approach? Is there a better way to accomplish this?

**Comment by joepuzzo** [comment]
The way you are doing this is fine. There are more ways of exposing the other password field but this works. One way would be to wrap your second validate function in a function that passes the password field in with just formApi.password but its really half dozen of the other. Another solution would be to use a nested field and pass in a full validation function to it that dealt with both values
