### ISSUE TITLE
Radio dont work without RadioGroup

### ISSUE THREAD

**Issue by Fetzner** [react-tools/react-form#289]
I think is better change Basic usage because doesn't work.
If you try to use Radio Component without RadioGroup you get an error

      <RadioGroup>
        <label>
          Male <Radio field='gender' value="male" />
        </label>
        <label>
          Female <Radio field='gender' value="female" />
        </label>
      </RadioGroup>

not 

"<div>
        <label>
          Male <Radio field='gender' value="male" />
        </label>
        <label>
          Female <Radio field='gender' value="female" />
        </label>
      </div>"

Thanks

![image](https://user-images.githubusercontent.com/4790802/37960215-f873da82-31ac-11e8-842e-24337d6f14e4.png)

**Comment by joepuzzo** [comment]
wow thank you so much for noticing this... i cant believe i missed this. Just pushed out updated README!
