### ISSUE TITLE
Strange behavior with defaultValues

### ISSUE THREAD

**Issue by shauravg** [react-tools/react-form#293]
I am using version 3.4.4

In my parent component, I am creating a defaultValues object in the constructor. This object is either empty if the user is not logged in or has values if the user is logged in. I tried both with having this object be part of the component state and as a class variable. The values needed to build the defaultValues object are being read from a cookie so its not an async function. In my render function, I have:

`<Form 
					component={ContactFormFields} 
					onSubmit={this.handleSubmit} 
					validate={this.handleFormValidation}
					defaultValues={this.defaultValues}
				/> `

When the page first loads, the default values do not show up. When I click on one of the text input fields that does have a default value assigned and take the focus away from it, then the default value appears. Any thoughts on whether I am misusing the defaultValues prop or there is something wrong?

**Comment by joepuzzo** [comment]
Hmm interesting.. I just created this code sandbox and this seems to work fine there. https://codesandbox.io/s/vj781lzrq0

**Comment by joepuzzo** [comment]
Are you sure you have no console errors?

**Comment by shauravg** [comment]
I don't have any console errors and I am not pulling the default values from an async function so I do it have them available on first render. Let me double check everything by comparing to your code sample and get back to you.

**Comment by joepuzzo** [comment]
Also try with the latest version 3.5.0

**Comment by shauravg** [comment]
Sorry, this issue was on my side. I was getting default values from a cookie and it indeed was not available on the first render. I am going to instead use setValue. Thanks for your help and this awesome library!
