### ISSUE TITLE
How do you do array validation?

### ISSUE THREAD

**Issue by kasuboski** [react-tools/react-form#294]
Say I need to make sure an array of fields has at least one item. The only way I see to do that now is with the validate function at the form level. Am I correct in this?

My fields are dynamically generated so I don't necessarily know their names. I'm thinking I'll have to loop through the values and if it's an array add my validation there.

It seems like there should be an easier way, but I'm missing it.

**Comment by joepuzzo** [comment]
I belive you are correct. Best way would be to loop through and check each value. React form does not keep track of the length of the arrays for you or weather or not the array contains a value. Maybe you could write some fancy method that kept track of if your array had a value but its not in the lib.

**Comment by kasuboski** [comment]
Thanks. I was able to make this work just checking if the library had a value for my expected fields.

I'm running into an issue now where the library doesn't seem to have support for differentiating form level errors from field level errors.

I can also figure this out on my own, but wanted to make sure I didn't miss something.

**Comment by joepuzzo** [comment]
There is a pull request out for fixing this differenciation will get it in soon

**Comment by kasuboski** [comment]
Can you link the PR?

**Comment by joepuzzo** [comment]
Try now with V3.5.0

**Comment by joepuzzo** [comment]
Does this work now... can i close?

**Comment by kasuboski** [comment]
Sorry didn't get a chance to confirm yet. You can still close if you want
to. I ended up going a different route.

On Apr 10, 2018 4:04 PM, "Joe Puzzo" <notifications@github.com> wrote:

Does this work now... can i close?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/react-tools/react-form/issues/294#issuecomment-380110429>,
or mute the thread
