### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by DanFerro** [react-tools/react-form#297]
Does anyone have an example of a custom input with a range input? I can't quite get the value to update. 

```
<input
  type="range"
  min={min}
  max={max}
  step={step}
  value={value}
  onChange={e => {
    setValue(e.target.value);
    if (onChange) {
      onChange(e.target.value, e);
    }
    setTouched();
  }}
  className="slds-slider__range"
  {...rest}
/>
```

**Comment by joepuzzo** [comment]
I would recommend creating your own custom input https://react-form.js.org/#/custom-input

**Comment by joepuzzo** [comment]
Closing as this is not an issue but for help here is a code sandbox that does what you need https://codesandbox.io/s/vvql3wjon0
