### ISSUE TITLE
fieldApi 'touched' property is an empty object instead of bool before being set?

### ISSUE THREAD

**Issue by davejm** [react-tools/react-form#300]
Repro: https://codesandbox.io/s/72wqvxwyj0

As you can see in the console, when the form loads, the touched property of the fieldApi is an empty object rather than false. Am I doing something wrong here?

**Comment by davejm** [comment]
@joepuzzo

**Comment by davejm** [comment]
Could it be to do with this change? https://github.com/react-tools/react-form/commit/23d73771df976306120f32b80a3819018337c661#diff-07a63ede6fe55fca89398d42da737369L282

**Comment by joepuzzo** [comment]
I believe this was an intentional change @tannerlinsley am i correct in saying it should have always been an empty object? and this was a fix?

**Comment by davejm** [comment]
On the field API? If this was a fix then I think the documentation is probably a bit misleading as you'd expect a boolean. In any case, an empty object is truthy so it's doubly confusing

**Comment by joepuzzo** [comment]
Touched is not what you may think it is.. touched is an object where the key is the field and the value is if that field has been touched.. the docs say “Object is empty by default. ” and explain this. If it was undefined before that was a bug. That being said we should prob add another state attribute that says if form is dirty

**Comment by davejm** [comment]
On this page https://react-form.js.org/#/custom-input the `touched` field is true? Also "The difference is that fieldApis functions are scoped to the field, and it only has a subset of the formApis functions." I think we might be talking at odds here. I'm talking about the fieldApi not the formApi

**Comment by joepuzzo** [comment]
Ahh im sorry i thought we were talking about form level not field level

**Comment by joepuzzo** [comment]
You are totally right i will fix right away

**Comment by joepuzzo** [comment]
This is fixed in V3.5.1 :) thanks for bearing with me !
