### ISSUE TITLE
Question. 3.0.0 release notes

### ISSUE THREAD

**Issue by mykhailo-riabokon** [react-tools/react-form#303]
Hey!

I am using react-form version 2 and thinking about migration to version 3. I checked release notes and have a question.

Release note says:
<img width="800" alt="screen shot 2018-04-09 at 11 03 40" src="https://user-images.githubusercontent.com/10687640/38486442-b9dbda66-3be5-11e8-9af4-e145fe9b7f45.png">

But I did not find `withFormField` method in `index.js` exports. The only mention of if can be found in 
<img width="479" alt="screen shot 2018-04-09 at 11 05 11" src="https://user-images.githubusercontent.com/10687640/38486501-f4447140-3be5-11e8-9a0e-2393ca485397.png">

But there is a `withFieldApi `, so is it the right one to use?

Thank you in advance.

**Comment by joepuzzo** [comment]
This is `withField` sorry we must have changed it and then not updated the release notes
