### ISSUE TITLE
Provide a way to search through all the docs

### ISSUE THREAD

**Issue by theodorDiaconu** [react-tools/react-form#304]
I did something with: https://www.algolia.com/ it's easy (not advertising it, used it myself in www.meteor-tuts.com)

**Comment by joepuzzo** [comment]
Hmm looks cool there are not much docs yet so i don't know how necessary this would be but that link you posted is pretty cool. It looks like you have to pay for something tho? Would def rather use something open source.

**Comment by theodorDiaconu** [comment]
@joepuzzo it's free let me point you to the code.

https://github.com/cult-of-coders/meteor-tuts/blob/master/themes/meteor/layout/partials/sidebar.ejs#L18 

https://github.com/cult-of-coders/meteor-tuts/blob/master/themes/meteor/layout/layout.ejs#L93

**Comment by theodorDiaconu** [comment]
Regarding necessity, believe me, if this becomes more complex, more options, people won't remember the full api in their head, they come to docs and search.

**Comment by 0xdevalias** [comment]
Technically already do go back to the docs constantly, and the current layout of them makes finding things somewhat annoying at times. Feels unintuitive.

**Comment by joepuzzo** [comment]
joepuzzo.github.io/informed. Created new lib and it has this ability in docs.
