### ISSUE TITLE
Trigger validation manually

### ISSUE THREAD

**Issue by laurenz-glueck** [react-tools/react-form#322]
It would be really helpful if there would be a method on the formApi to trigger the form validation manually. 

I have seen there is a "validateAll" function in the Form.js - why not making this available through the formApi? :)

**Comment by joepuzzo** [comment]
Try out https://joepuzzo.github.io/informed. I rewrote this library and will now be supporting `informed` instead. And if you check out section on validation control you can do what you want!!!

**Comment by laurenz-glueck** [comment]
@joepuzzo thanks for your response - just to be clear, does that mean that react-from is not longer maintained?

**Comment by joepuzzo** [comment]
So I personally will no longer maintain it. But i think the plan is to depricate it. React form became a little to bloated so i decided to rewrite it for the 90% use case. Rather than try to pack every feature under the sun in it haha
