### ISSUE TITLE
Issue resetting `submitting` flag on error

### ISSUE THREAD

**Issue by fruitraccoon** [react-tools/react-form#325]
Currently there appears to be a small issue in the following situation:
- when an error is thrown during a submit
- there is no `onSubmitFailure` handler

This causes the `submitting` flag to not be reset to false.

The issue is that if there is no `onSubmitFailure` handler, then the error is thrown, which then skips the code that resets the flag.  The relevant code is here: https://github.com/react-tools/react-form/blob/c2337923284425e10620add45647e332be9c0459/src/components/Form.js#L472

The work around is to always have an `onSubmitFailure` handler, even if it does nothing.

**Comment by joepuzzo** [comment]
Try out https://joepuzzo.github.io/informed. I rewrote this library and will now be supporting `informed` instead.
