### ISSUE TITLE
withFieldApi Returns Empty

### ISSUE THREAD

**Issue by cjkoepke** [react-tools/react-form#326]
Hi, I'm trying to figure out why using the `withFieldApi` HOC is returning an empty `fieldApi` prop object. What are some of the reasons that this would happen?

I know for a fact that the field name is available, because if I manually retrieve the value using `formApi.getFormState().values[field.name]` it returns the correct value.

I'm sure more information is probably needed but just hoping to be pointed in the right direction.

**Comment by joepuzzo** [comment]
Hey @cjkoepke so im no longer supporting this lib but Im working on a newer sleaker version that also has withFieldApi and keeps basically the same interface. I can let you know when i get the first release out but off the top of my head you may be passing in the wrong field value. Can you post how you are using withFieldApi ?

**Comment by cjkoepke** [comment]
@joepuzzo Thanks for letting me know! Is the entire lib no longer maintained, or is just by someone else? This is currently how I'm trying to get access, via the export:

```js
export default props => {
	const RowFormApi = withFormApi(Row)
	const RowFieldApi = withFieldApi(props.data.name)(RowFormApi)
	return <RowFieldApi {...props} />
}```

I have verified that `props.data.name` is actually the correct field name.

**Comment by joepuzzo** [comment]
Hmm this should be working what does row look like.. and is this rendered within a `<Form>`?

**Comment by joepuzzo** [comment]
Oh and yeah its been maintained by @tannerlinsley and I but i think we are going to offload the lib to `informed` once i get a V1 release out. Which again, should have an almost identical interface.. i will be adding a changelog that talks about the diffs/breaking changes

**Comment by cjkoepke** [comment]
Awesome. So to give better context this is how it's setup.

**Main component:**
```js
<Form defaultValues={tab.initialValues} onSubmit={onSubmit} className={`field-switch-form`}>
    {formApi => (
        <form onSubmit={formApi.onSubmit}>
            <table className="patient-information">
                <colgroup>
                    <col width="300"></col>
                </colgroup>
                <tbody>
                    {sections && sections.map((section, index)  => {
                        return <Rows key={index} field={section} activeField={this.state.activeField} />
                    })}
                </tbody>
            </table>
        </form>
    )}
</Form>
```

`Rows` is a standard React Component:

```js
class Rows extends Component {
	constructor(props) {
		super(props)
	}

        shouldComponentUpdate(nextProps) {
		return nextProps.activeField === this.props.field.key
	}

    render() {
        const FieldSwitchWithApi = withFieldApi(field.name)(FieldSwitch)
        return (
            <tr>
                <td>
                    {field.label}
                </td>
                <td>
                    <FieldSwitchWithApi data={field} />
                </td>
            </tr>
        )
    }
```

I'm currently accessing the API from inside `FieldSwitch` like above (since `withFieldApi` isn't working). If I remove the `Field` component and try to wrap `FieldSwitch` in `withFieldApi` it passes the fieldApi prop, but just returns a blank object:

![screen shot on 2018-05-25 at 09_08_36](https://user-images.githubusercontent.com/2815568/40551853-4dd2ab94-5ffb-11e8-811a-58e3aaaa6d68.png)

I can successfully bypass this and manually pass it as a prop using:

```js
<Field field={field.name}>
    {api => <FieldSwitch data={field} fieldApi={api} />}
</Field>
```

Hope that helps give context — it's weird that using the `Field` component works, since as far as I can tell, `withFieldApi` is just a wrapper function to do the same thing.

**Comment by joepuzzo** [comment]
I would recommend migrating to https://joepuzzo.github.io/informed

**Comment by cjkoepke** [comment]
@joepuzzo When do you think Informed will be ready for production?

**Comment by joepuzzo** [comment]
Its ready now :)

**Comment by joepuzzo** [comment]
Just read the changelog so you know whats gone and what changed
