### ISSUE TITLE
It is good to have name or field in validator function call

### ISSUE THREAD

**Issue by kevalbhatt** [react-tools/react-form#340]
My quetion is **"How I can show field name in validation message? "**

>**use case**

I have created custom input for showing the validation message I followed the same example https://react-form.js.org/#/custom-input

This is my validation function.

```
const requiredValidate = (value, field) => {
  return !value
    ? `${field} is required`
    : null;
}
```

I want to show the name of the field in error message but based on code it is not possible to show field name

` 74: const result = validator(Utils.get(getState().values, field))`

https://github.com/react-tools/react-form/blob/master/src/redux/actions.js#L74

is it good if we do something like this.

```
export function validate ({ field, validator, name }) {
  return (dispatch, getState) => {
    if (!validator || validator === Utils.noop) {
      return
    }
    // Call the validation function and clean the result
    const result = validator(Utils.get(getState().values,field), field)
   //or 
   const result = validator(Utils.get(getState().values,field), name)
```

**Comment by joepuzzo** [comment]
Just create a function closure and pass the field name in ( value ) => someValidateFunction( value, 'myfieldname')

**Comment by kevalbhatt** [comment]
Thanks @joepuzzo  it worked! 👍
