### ISSUE TITLE
nestedForms values get deleted when nested form is in error state.

### ISSUE THREAD

**Issue by joepuzzo** [react-tools/react-form#88]
This occurs in your example located https://react-form.js.org/#/story/kitchen-sink as well. 

To recreate. 
1. Fill out the address field
2. Delete the content from one of the fields
3. All the values will disappear

**Comment by tannerlinsley** [comment]
I'm assuming you mean I need to have more than the address field filled out to "Delete the content from one of the fields":
I filled out the `city` field, then filled out the `address` field, then deleted the content out of the `city` field.
I didn't experience this issue.  Are there more precise instructions to replicate the issue?

**Comment by joepuzzo** [comment]
Fill out all three fields, then delete everything from one of them. 

1. Fill out street 
2. Fill out city
3. Fill out state
4. Backspace everything from city

**Comment by tannerlinsley** [comment]
Good find!  I'll look into this asap

**Comment by joepuzzo** [comment]
This has something to do with setNestedError in the NestedForm. I removed that line locally and it no longer clears it. Not sure why setNestedError would be causing this.

**Comment by joepuzzo** [comment]
Hmm could have something do do with setNestedError causing a re-render.

**Comment by joepuzzo** [comment]
I figured out the issue!

When you call set nested error it sets the parent forms 'nestedFormFields' field to undefined. Then, because getValue is called, it sets all of the values in the form to undefined. Removing this is the easy fix but it may break other users who use this functionality to set the defaultValues. Any ideas on how we could fix this with ought breaking that functionality?
```
return React.cloneElement(children, {
          ...rest,
          /* Let the parent form set defaultValues */
          values: getValue(), <<<<<<<< THIS RIGHT HERE ( remove and problem solved )
          /* Respond to the parent form's dirty submission attempts */
          touched: getTouched(),
          /* Notify the parent of any nestedForm-level errors and values */
          onChange: ({ values, errors }, props, initial) => {
            errors ? setNestedError(true) : setNestedError(false)
            setValue(values, initial)
          },
        })
```

**Comment by rowdyroad** [comment]
I've spent about a day to figure it out.
I think, problem is in **errors** variable. If it equals {} so nestederrors is true.


My fix here, I can make PR

`return React.cloneElement(children, {
          ...rest,
          /* Let the parent form set defaultValues */
          values: getValue(), <<<<<<<< THIS RIGHT HERE ( remove and problem solved )
          /* Respond to the parent form's dirty submission attempts */
          touched: getTouched(),
          /* Notify the parent of any nestedForm-level errors and values */
          onChange: ({ values, errors }, props, initial) => {
            **errors && Object.keys(errors).length > 0 ? setNestedError(true) : setNestedError(false)**
            setValue(values, initial)
          },
        })`

**Comment by joepuzzo** [comment]
I have rewritten this form library and solved many of the issues including this one. See npm: https://www.npmjs.com/package/react-savage-form and docs are located here https://react-savage-form.cfapps.io/

**Comment by joepuzzo** [comment]
Update: Working on getting V2 of react-form rolled out. This problem will be solved soon!

**Comment by joepuzzo** [comment]
Fixed in V2
