### ISSUE TITLE
1.3.0 Got warning "changing a controlled input of type checkbox to be uncontrolled", and failed in `setAllValues` on dict field.

### ISSUE THREAD

**Issue by houkanshan** [react-tools/react-form#91]
Hi, I just upgraded to 1.3.0 from 1.2.8, but there's something broken. I have a webpackbin for this:

https://www.webpackbin.com/bins/-KpZ8CHU6WKnV0wQsqZw

In case that page would be outdated, here is the test code and test steps:

```jsx
import React from 'react'
import { render } from 'react-dom'
import { Form, Checkbox } from 'react-form'

const defaultValues = {
  checkbox0: { a: true }
}

render(<Form defaultValues={defaultValues}>{
  ({setAllValues, values}) => <form>
    <p>1. open developer tools</p>
    <p>2. check "b" (got a warning)</p>
    <p>3. click "reset" ("a" is still checked)</p>
    <hr/>
    <Checkbox field={['checkbox0', 'a']} />a
    <hr/>
    <Checkbox field={['checkbox0', 'b']} />b
    <hr/>
    <pre>{JSON.stringify(values, null, 2)}</pre>
    <button type='button' onClick={() => setAllValues({checkbox0: {}})}>reset</button>
  </form>
}</Form>, 
document.getElementById('root'))
```

So the problem with is:

First I got a waring from React after I checked a `<Checkbox/>`:

![image](https://user-images.githubusercontent.com/657962/28455834-fba073fc-6e32-11e7-96d8-aedebf0e834a.png)

and when I want to use `setAllValues` with nested fields like `field={['checkboxs', 'a']}`, the form just change to its initial state.

react@15.6.1
react-dom@15.6.1
react-form@1.3.0

Thanks!

**Comment by joepuzzo** [comment]
This is fixed in latest version of V2.
