### ISSUE TITLE
Question: Accessing form data outside of form?

### ISSUE THREAD

**Issue by GoldenRust** [react-tools/react-form#93]
Hi,

Is there a way to access the form data outside of the form?

The docs mention using an external state manager, this project is using redux, but I'd like to keep this form data in the component, not in redux.

So far I've set something up that looks like this:

```javascript

saveFormState = (data) => {
  this.setState({formData: data})
}

render() {
return(
  <Form 
    saveState={data => this.saveFormState(data)}
    onSubmit={values => console.log(values)}
  >
  {({onSubmit}) => {
    <form onSubmit={submitForm}>
      {//form elements dynamically generated from api}
    </form>
  }}
)
}
```

I'm not sure if there's a better way to do this.

Thanks.

**Comment by thg303** [comment]
@GoldenRust you may set `ref` on the form, and access it's `state` object. that allows you to access everything

**Comment by tannerlinsley** [comment]
@thg303 is right. Closing for now.
